function checkIconsVersion(a){var b=opendb();createDataTable(b);if(b){var c=function(b,c){var d=!0,f=null;lpGetPref("icons",-1);0<c.rows.length&&lpGetPref("icons",-1)==a&&(d=!1,f=c.rows.item(0).data);null==f||d?downloadIcons():processIcons(f)};if(g_indexeddb){var d={rows:{item:function(a){return this[a]},length:0}};b.transaction("LastPassData","readonly").objectStore("LastPassData").openCursor(IDBKeyRange.only(db_prepend(g_username_hash)+"_icons")).onsuccess=function(a){(a=a.target.result)?(d.rows[d.rows.length]=
a.value,d.rows.length++,a["continue"]()):c(null,d)}}else b.transaction(function(a){a.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"icons"],c,function(a,b){console_log(b)})})}else downloadIcons()}function downloadIcons(){lpMakeRequest(base_url+"geticon.php","versionchrome=1&username="+en(g_username),lpIconResponse,null)}
function downloadBigIcons(a){var b="big=1&versionchrome=1&username="+en(g_username);a&&(b+="&domain="+en(a));lpMakeRequest(base_url+"geticon.php",b,lpBigIconResponse,null)}function lpIconResponse(a){if(4==a.readyState&&(200==a.status&&a.responseText)&&!("latest"==a.responsetext||"nodata"==a.responsetext)){var b=a.responseText.split("\n");a=b[0].split("=")[1];b=b[1];lpPutUserPref("icons",a);lpWriteAllPrefs();lpSaveData(b,"icons");processIcons(b)}}
function lpBigIconResponse(a){if(4==a.readyState&&(200==a.status&&a.responseText)&&!("latest"==a.responsetext||"nodata"==a.responsetext))processIcons(a.responseText,!0),saveBigIcons()}function getBigIconKeyIfMissing(a){null==BigIconList&&LoadBigIconList();var b=hostof(a),c=AES.bin2hex(b);if("undefined"!=typeof BigIconList[c])return"undefined"==typeof g_bigicons[b]?b:null;a=lp_gettld_url(a);b=AES.bin2hex(a);return"undefined"!=typeof BigIconList[b]?"undefined"==typeof g_bigicons[a]?a:null:null}
function checkBigIconsVersion(a,b,c){var d=!0,e;for(e in g_bigicons){d=!1;break}if(d&&!b){var g=opendb();createDataTable(g);if(g){var h=function(b,d){var e=null;0==d.rows.length||null==d.rows.item(0).data?downloadBigIcons("all"):(e=d.rows.item(0).data,processIcons(e,!0),checkBigIconsVersion(a,!0,c))};if(g_indexeddb){var f={rows:{item:function(a){return this[a]},length:0}};g.transaction("LastPassData","readonly").objectStore("LastPassData").openCursor(IDBKeyRange.only(db_prepend(g_username_hash)+"_bigicons")).onsuccess=
function(a){(a=a.target.result)?(f.rows[f.rows.length]=a.value,f.rows.length++,a["continue"]()):h(null,f)}}else g.transaction(function(a){a.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"bigicons"],h,function(a,b){console_log(b)})})}}else if(a)b=getBigIconKeyIfMissing(a),null!=b&&downloadBigIcons(b);else{d=!1;e=[];var j=[];for(g in g_sites)d=!0,b=getBigIconKeyIfMissing(g_sites[g].url),null!=b&&"undefined"==typeof j[b]&&(j[b]=1,e[e.length]=b);
!d&&!c?downloadBigIcons("all"):e.length&&downloadBigIcons(e.join(","))}}function processIcons(a,b){if(a)for(;!(10>a.length);){var c=/lp([^:]+):([^:]+):/.exec(a);if(!c||3!=c.length)break;var d=c[1],e=c[2],c=parseInt(e);if(isNaN(c))break;e="lp"+d+":"+e+":";b?g_bigicons[AES.hex2bin(d)]=lpsubstring(a,e.length,e.length+c):(g_icons[d]=lpsubstring(a,e.length,e.length+c),g_icons_length++);a=a.substring(e.length+c)}}
function saveBigIcons(){var a="",b;for(b in g_bigicons)var c=g_bigicons[b],a=a+("lp"+AES.bin2hex(b)+":"+c.length+":"+c);b=opendb();createDataTable(b);b&&(g_indexeddb?b.transaction("LastPassData","readwrite").objectStore("LastPassData").put({username_hash:db_prepend(g_username_hash),type:"bigicons",data:a,usertype:db_prepend(g_username_hash)+"_bigicons"}):b.transaction(function(b){b.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, ?, ?)",[db_prepend(g_username_hash),"bigicons",
a],function(){console_log("server.js : inserted")},function(a,b){console_log(b)})}))};
