document.getElementById("lp_docwrite_lp_toolstrip1")&&(document.getElementById("lp_docwrite_lp_toolstrip1").innerHTML=gs("Login to LastPass"));document.getElementById("lp_docwrite_lp_toolstrip2")&&(document.getElementById("lp_docwrite_lp_toolstrip2").innerHTML=gs("LastPass"));document.getElementById("lp_docwrite_lp_toolstrip7")&&(document.getElementById("lp_docwrite_lp_toolstrip7").innerHTML="<label for='advanced'>"+gs("Show Advanced Options")+"</label>");
document.getElementById("lp_docwrite_lp_toolstrip8")&&(document.getElementById("lp_docwrite_lp_toolstrip8").innerHTML=gs("Password Length"));document.getElementById("lp_docwrite_lp_toolstrip9")&&(document.getElementById("lp_docwrite_lp_toolstrip9").innerHTML="<label for='pronounceable'>"+gs("Pronounceable")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip10")&&(document.getElementById("lp_docwrite_lp_toolstrip10").innerHTML="<label for='upper'>"+gs("A-Zupper")+"</label>");
document.getElementById("lp_docwrite_lp_toolstrip11")&&(document.getElementById("lp_docwrite_lp_toolstrip11").innerHTML="<label for='lower'>"+gs("a-zlower")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip12")&&(document.getElementById("lp_docwrite_lp_toolstrip12").innerHTML="<label for='digits'>"+gs("0-9")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip13")&&(document.getElementById("lp_docwrite_lp_toolstrip13").innerHTML="<label for='special'>"+gs("Special")+"</label>");
document.getElementById("lp_docwrite_lp_toolstrip14")&&(document.getElementById("lp_docwrite_lp_toolstrip14").innerHTML="<label for='mindigits'>"+gs("Minimum Digit Count")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip15")&&(document.getElementById("lp_docwrite_lp_toolstrip15").innerHTML="<label for='ambig'>"+gs("Avoid Ambiguous Characters")+"</label>");
document.getElementById("lp_docwrite_lp_toolstrip16")&&(document.getElementById("lp_docwrite_lp_toolstrip16").innerHTML="<label for='reqevery'>"+gs("Require Every Character Type")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip19")&&(document.getElementById("lp_docwrite_lp_toolstrip19").innerHTML=gs("Profile"));document.getElementById("lp_docwrite_lp_toolstrip20")&&(document.getElementById("lp_docwrite_lp_toolstrip20").innerHTML=gs("Credit cardformfill"));
document.getElementById("lp_docwrite_lp_toolstrip21")&&(document.getElementById("lp_docwrite_lp_toolstrip21").innerHTML=gs("Always Choose Profile and Credit Card"));document.getElementById("lp_docwrite_lp_toolstrip23")&&(document.getElementById("lp_docwrite_lp_toolstrip23").innerHTML=gs("LastPass detected a password change for"));document.getElementById("changepwtitle")&&(document.getElementById("changepwtitle").innerHTML=gs("Change Password"));
document.getElementById("lp_docwrite_lp_toolstrip24")&&(document.getElementById("lp_docwrite_lp_toolstrip24").innerHTML=gs("Please select which sites you wish to apply this change."));document.getElementById("yubititle")&&(document.getElementById("yubititle").innerHTML=gs("YubiKey Multifactor Authentication"));document.getElementById("lp_docwrite_lp_toolstrip27")&&(document.getElementById("lp_docwrite_lp_toolstrip27").innerHTML=gs("1. Insert your YubiKey in the USB-port with the USB-contact facing upward"));
document.getElementById("lp_docwrite_lp_toolstrip28")&&(document.getElementById("lp_docwrite_lp_toolstrip28").innerHTML=gs("2. Wait until your YubiKey touch-button shines with a steady light"));document.getElementById("lp_docwrite_lp_toolstrip29")&&(document.getElementById("lp_docwrite_lp_toolstrip29").innerHTML=gs("3. Hold your fingertip on the touch-button for 1 second"));
document.getElementById("lp_docwrite_lp_toolstrip30")&&(document.getElementById("lp_docwrite_lp_toolstrip30").innerHTML="<label for='lptrustyubi'>"+gs("Trust this computer for 30 days")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip31")&&(document.getElementById("lp_docwrite_lp_toolstrip31").innerHTML=gs("Please provide this computer a name"));document.getElementById("lp_docwrite_lp_toolstrip32")&&(document.getElementById("lp_docwrite_lp_toolstrip32").innerHTML=gs("I've lost my YubiKey device"));
document.getElementById("googtitle")&&(document.getElementById("googtitle").innerHTML=gs("Google Authenticator Multifactor Authentication"));document.getElementById("googdesc")&&(document.getElementById("googdesc").innerHTML=gs("Run the Google Authenticator application on your mobile device and enter the verification code in the input box below."));document.getElementById("lp_docwrite_lp_toolstrip35")&&(document.getElementById("lp_docwrite_lp_toolstrip35").innerHTML=gs("Enter Code:"));
document.getElementById("lp_docwrite_lp_toolstrip37")&&(document.getElementById("lp_docwrite_lp_toolstrip37").innerHTML="<label for='lptrustgoogleauth'>"+gs("Trust this computer for 30 days")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip38")&&(document.getElementById("lp_docwrite_lp_toolstrip38").innerHTML=gs("Please provide this computer a name"));document.getElementById("lp_docwrite_lp_toolstrip39")&&(document.getElementById("lp_docwrite_lp_toolstrip39").innerHTML=gs("I've lost my Google Authenticator device"));
document.getElementById("sesametitle")&&(document.getElementById("sesametitle").innerHTML=gs("Sesame Multifactor Authentication"));document.getElementById("lp_docwrite_lp_toolstrip41")&&(document.getElementById("lp_docwrite_lp_toolstrip41").innerHTML=gs("1. Run the LastPass Sesame application to generate a one time password"));document.getElementById("lp_docwrite_lp_toolstrip42")&&(document.getElementById("lp_docwrite_lp_toolstrip42").innerHTML=gs("2. Paste the one time password in the input box below and click 'Authenticate'"));
document.getElementById("lp_docwrite_lp_toolstrip43")&&(document.getElementById("lp_docwrite_lp_toolstrip43").innerHTML="<label for='lptrustsesame'>"+gs("Trust this computer for 30 days")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip44")&&(document.getElementById("lp_docwrite_lp_toolstrip44").innerHTML=gs("Please provide this computer a name"));document.getElementById("lp_docwrite_lp_toolstrip45")&&(document.getElementById("lp_docwrite_lp_toolstrip45").innerHTML=gs("I've lost my Sesame device"));
document.getElementById("gridtitle")&&(document.getElementById("gridtitle").innerHTML=gs("LastPass Grid Multifactor Authentication"));document.getElementById("lp_docwrite_lp_toolstrip48")&&(document.getElementById("lp_docwrite_lp_toolstrip48").innerHTML=gs("For each coordinate listed below, find the value on your grid and enter the value."));
document.getElementById("lp_docwrite_lp_toolstrip49")&&(document.getElementById("lp_docwrite_lp_toolstrip49").innerHTML="<label for='lptrustgrid'>"+gs("Trust this computer for 30 days")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip50")&&(document.getElementById("lp_docwrite_lp_toolstrip50").innerHTML=gs("Please provide this computer a name"));document.getElementById("lp_docwrite_lp_toolstrip51")&&(document.getElementById("lp_docwrite_lp_toolstrip51").innerHTML=gs("I've lost my grid"));
document.getElementById("lp_docwrite_lp_toolstrip52")&&(document.getElementById("lp_docwrite_lp_toolstrip52").innerHTML=gs("Security Question Multifactor Authentication"));document.getElementById("lp_docwrite_lp_toolstrip53")&&(document.getElementById("lp_docwrite_lp_toolstrip53").innerHTML=gs("Please answer the following question:"));
document.getElementById("lp_docwrite_lp_toolstrip56")&&(document.getElementById("lp_docwrite_lp_toolstrip56").innerHTML="<label for='lptrustsecurityquestion'>"+gs("Trust this computer for 30 days")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip57")&&(document.getElementById("lp_docwrite_lp_toolstrip57").innerHTML=gs("Please provide this computer a name"));document.getElementById("lp_docwrite_lp_toolstrip58")&&(document.getElementById("lp_docwrite_lp_toolstrip58").innerHTML=gs("I've forgot the answer"));
document.getElementById("oobtitle")&&(document.getElementById("oobtitle").innerHTML=gs("Multifactor Authentication"));document.getElementById("lp_docwrite_lp_toolstrip60")&&(document.getElementById("lp_docwrite_lp_toolstrip60").innerHTML=gs("Please complete multifactor authentication on your phone or mobile device."));document.getElementById("lp_docwrite_lp_toolstrip61")&&(document.getElementById("lp_docwrite_lp_toolstrip61").innerHTML=gs("I've lost my device"));
document.getElementById("lp_docwrite_lp_toolstrip62")&&(document.getElementById("lp_docwrite_lp_toolstrip62").innerHTML="<label for='lptrustoutofband'>"+gs("Trust this computer for 30 days")+"</label>");document.getElementById("lp_docwrite_lp_toolstrip63")&&(document.getElementById("lp_docwrite_lp_toolstrip63").innerHTML=gs("Please provide this computer a name"));
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){onLoad()});g_ismaxthon&&g_browseraction&&window.addEventListener("focus",function(){onLoad()});window.addEventListener("unload",function(){onUnload()});document.getElementById("lpbutton").addEventListener("click",function(){openmenu()});document.getElementById("closemole1").onclick=function(){closemole();return!1};document.getElementById("notifysavesitebtn").addEventListener("click",function(){savethesite()});
document.getElementById("notifyneverbtn").addEventListener("click",function(a){clicknever(a)});document.getElementById("notifyclosebtn").addEventListener("click",function(){closemole()});document.getElementById("notifychangeconfirmbtn").addEventListener("click",function(){changeconfirm()});document.getElementById("notifychangesavenewsitebtn").addEventListener("click",function(){savethesite()});document.getElementById("notifyfeedbackbtn").addEventListener("click",function(){getBG().openURL(getBG().base_url+
"feedback.php");closemole()});document.getElementById("notifytryagainbtn").addEventListener("click",function(){getBG().VaultToggle.useVault4_0()?window.location="extensionLogin.html":(openmole("lpinlinelogin"),document.body.style.background="white")});document.getElementById("notifycreateaccountbtn").addEventListener("click",function(){getBG().openURL(getchromeurl("welcome.html"));closemole()});document.getElementById("notifydisablebtn").addEventListener("click",function(){getBG().openURL(getBG().base_url+
g_notifydata.multifactor_disable_url);closemole()});document.getElementById("notifydisablesinglebtn").addEventListener("click",function(){getBG().disable_single_factor();closemole()});document.getElementById("notifystarttrialbtn").addEventListener("click",function(){getBG().start_trial();closemole()});document.getElementById("notifyyesbtn").addEventListener("click",function(){getBG().openURL(g_notifydata.upgradeurl);closemole()});document.getElementById("notifynobtn").addEventListener("click",function(){closemole()});
document.getElementById("lpform2").onsubmit=function(){return!1};document.getElementById("chooseprofileccok").addEventListener("click",function(){dochooseprofilecc()});document.getElementById("chooseprofilecccancel").addEventListener("click",function(){closemole()});document.getElementById("lpform3").onsubmit=function(){return!1};document.getElementById("changepwchange").addEventListener("click",function(){dochangepw()});document.getElementById("changepwclose").addEventListener("click",function(){closemole()});
document.getElementById("lpform4").onsubmit=function(){otpcheck();return!1};document.getElementById("lptrustyubi").addEventListener("click",function(){fix_height("yubikey",this.checked);document.getElementById("labelyubi").style.display=this.checked?"block":"none"});document.getElementById("lostkey").onclick=function(){lostkey();return!1};document.getElementById("lpform5").onsubmit=function(){googleauthotpcheck();return!1};document.getElementById("lpform9").onsubmit=function(){outofbandotpcheck();
return!1};document.getElementById("lpform8").onsubmit=function(){securityquestionotpcheck();return!1};document.getElementById("lptrustgoogleauth").addEventListener("click",function(){fix_height("googleauth",this.checked);document.getElementById("labelgoogleauth").style.display=this.checked?"block":"none"});document.getElementById("lptrustoutofband").addEventListener("click",function(){fix_height("outofband",this.checked);document.getElementById("labeloutofband").style.display=this.checked?"block":
"none"});document.getElementById("lptrustsecurityquestion").addEventListener("click",function(){document.getElementById("labelsecurityquestion").style.display=this.checked?"block":"none"});document.getElementById("googleauthlostkey").onclick=function(){googleauthlostkey();return!1};document.getElementById("outofbandlostkey").onclick=function(){outofbandlostkey();return!1};document.getElementById("securityquestionlostkey").onclick=function(){securityquestionlostkey();return!1};document.getElementById("lpform6").onsubmit=
function(){sesameotpcheck();return!1};document.getElementById("lptrustsesame").addEventListener("click",function(){fix_height("sesame",this.checked);document.getElementById("labelsesame").style.display=this.checked?"block":"none"});document.getElementById("sesamelostkey").onclick=function(){sesamelostkey();return!1};document.getElementById("lpform7").onsubmit=function(){gridcheck();return!1};document.getElementById("lpgridinput1").addEventListener("keyup",function(){0<this.value.length&&document.getElementById("lpgridinput2").focus()});
document.getElementById("lpgridinput2").addEventListener("keyup",function(){0<this.value.length&&document.getElementById("lpgridinput3").focus()});document.getElementById("lpgridinput3").addEventListener("keyup",function(){0<this.value.length&&document.getElementById("lpgridinput4").focus()});document.getElementById("lpgridinput4").addEventListener("keyup",function(){0<this.value.length&&document.getElementById("gridauth").focus()});document.getElementById("lptrustgrid").addEventListener("click",
function(){document.getElementById("labelgrid").style.display=this.checked?"block":"none"});document.getElementById("lostgrid").onclick=function(){lostgrid();return!1}});
function setup_event_handlers(){for(var a=1;2>=a;a++)for(var b=document.getElementsByTagName(1==a?"div":"img"),c=0;c<b.length;c++){if(b[c].id)if(0==b[c].id.indexOf("opendelete"))b[c].onclick=function(){menuaction(this.id,this.getAttribute("data-lptitle"))};else if(0==b[c].id.indexOf("menurowmatch"))b[c].onclick=0==b[c].id.indexOf("menurowmatchedit")||0==b[c].id.indexOf("menurowmatchfill")||0==b[c].id.indexOf("menurowmatchcopyusername")||0==b[c].id.indexOf("menurowmatchcopyurl")||0==b[c].id.indexOf("menurowmatchcopypassword")||
0==b[c].id.indexOf("menurowmatchcopynote")||0==b[c].id.indexOf("menurowmatchdelete")||0==b[c].id.indexOf("menurowmatchgotourl")?function(){menuaction("match"+this.id.substring(12),this.getAttribute("data-lptitle"))}:function(){menuaction("matchopen"+this.id.substring(12),this.getAttribute("data-lptitle"))};else if(0==b[c].id.indexOf("match"))b[c].onclick=function(){menuaction(this.id)};else if(0==b[c].id.indexOf("menurow")){var d=b[c].getAttribute("data-lpmenurowtype");d&&(1==d?b[c].onclick=function(){menuopen(this.id.substring(7),
null,this.getAttribute("data-lptitle"))}:2==d?b[c].onclick=function(){menuaction(this.getAttribute("data-lpcmd"))}:3==d?(b[c].onclick=function(){menuaction(this.id.substring(7),this.getAttribute("data-lptitle"))},b[c].oncontextmenu=function(){return rightclickmenuaction(this.id.substring(7))}):4==d&&(b[c].onclick=function(){deletenever(this.id.substring(7))}))}b[c].getAttribute("menu-lpwidth")&&(b[c].style.width=b[c].getAttribute("menu-lpwidth")+"px");b[c].getAttribute("menu-lpbackground")&&(b[c].style.background=
"url("+b[c].getAttribute("menu-lpbackground")+") no-repeat")}}
function pwUpkeep(a){"undefined"!==typeof a&&(pronounceable=document.getElementById("pronounceable"),reqevery=document.getElementById("reqevery"),idname="undefined"==typeof a.id&&"undefined"!==typeof a.target?a.target.id:a.id,"reqevery"==idname?(document.getElementById("mindigits").readOnly=!1,document.getElementById("mindigits").style.backgroundColor="#ffffff",document.getElementById("upper").checked=!0,document.getElementById("lower").checked=!0,document.getElementById("digits").checked=!0,document.getElementById("special").checked=
!0,document.getElementById("digits").disabled=!1,document.getElementById("special").disabled=!1,document.getElementById("ambig").disabled=!1):"pronounceable"==idname&&(document.getElementById("mindigits").style.backgroundColor="#d1d1d1",document.getElementById("mindigits").readOnly=!0,document.getElementById("digits").checked=!1,document.getElementById("special").checked=!1,document.getElementById("ambig").checked=!1,document.getElementById("digits").disabled=!0,document.getElementById("special").disabled=
!0,document.getElementById("ambig").disabled=!0));dogenerate()}
function setup_generate_handlers(){document.getElementById("lpform1").onsubmit=function(){return!1};document.getElementById("advbutton").addEventListener("click",function(){showHideAdvIFrame(document)});document.getElementById("advlabel").addEventListener("click",function(){showHideAdvIFrame(document)});document.getElementById("advanchor").onclick=function(){return!1};document.getElementById("generatebutton").addEventListener("click",function(){onhidegenerate();dogenerate()});document.getElementById("copypwbutton").addEventListener("click",
function(){docopypw()});document.getElementById("generatesave").addEventListener("click",function(){onhidegenerate();dosave()});document.getElementById("generateclose").addEventListener("click",function(){onhidegenerate();closemole()});document.getElementById("reqevery").addEventListener("click",function(a){pwUpkeep(a)});document.getElementById("pronounceable").addEventListener("click",function(a){pwUpkeep(a)});document.getElementById("length").addEventListener("change",function(a){pwUpkeep(a)});
document.getElementById("special").addEventListener("click",function(a){pwUpkeep(a)});document.getElementById("digits").addEventListener("click",function(a){pwUpkeep(a)});document.getElementById("ambig").addEventListener("click",function(a){pwUpkeep(a)});document.getElementById("upper").addEventListener("click",function(a){pwUpkeep(a)});document.getElementById("lower").addEventListener("click",function(a){pwUpkeep(a)});document.getElementById("mindigits").addEventListener("keyup",function(a){pwUpkeep(a)});
pwUpkeep()}function fix_height(a,b){a=document.getElementById(a);a.style.height=parseInt(LP_getComputedStyle(window,a).height.replace("px",""))+20*(b?1:-1)+"px"};
