var SHOULD_DO_LOGIN_ONLY=!0,SHOULD_DO_ALWAYS=!1;
function popupfill_shoulddofield(a,b,d){var c=["lpcurrpasselt","lpcurruserelt"];if(do_experimental_popupfill&&!(null==b||"undefined"==typeof b.type||"hidden"==b.type)&&("text"==b.type||"password"==b.type||"email"==b.type||!d&&"tel"==b.type||!d&&"url"==b.type||!d&&"textarea"==b.type)){var e=LP_pickFieldName(a,b);if(lp_in_array(e,c))return decision_log(a,"DE28",{param1:e}),!1;if(is_search_field(a,b,!d)||is_date_field(b)||LP_looksLikeOTPField(a,b)||LP_explicit_ignored(a,b)||LP_implicit_ignored(a,b)||
LP_isCaptchaField(b))return!1;if(d){if(!chk_form_has_password(a,b.form)&&!checkDocumentForLoginOrphans(a))return verbose&&(b=LP_pickFormName(a,b.form),decision_log(a,"DE29",{param1:b})),!1;if(b.form&&is_shopping_form(a,b.form)&&g_aspx_hack&&(isASPpage()&&2<a.getElementsByTagName("form").length||!isASPpage()))return!1}return!0}return!1}
function chk_form_ask_generate(a,b,d){var c=null;if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;var e=LP_pickFormName(a,b),f;if(!d&&(f=formcacheget(a,e,"ask_generate"),null!=f))return f;var j="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(j.length<MAX_FORM_ELEMENTS_HARD,"form "+e+" has too many inputs");if(j.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,e,"is_login",!1),!1;try{var l=gettldcached(a.location.href)}catch(n){return!1}var g=
f=0,q=3;d&&(q=2);g_aspx_hack&&isASPpage()&&(q=7);if("tumblr.com"==l&&(tumblr_action_btn=a.getElementById("signup_forms_submit"),null!=tumblr_action_btn)){d=tumblr_action_btn.getElementsByTagName("SPAN");var s;for(s=0;s<d.length;s++)if(0<=d[s].className.indexOf("login_btn")&&checkIsDisplayed(a,d[s],0,l))return!1}if(!checkIsDisplayed(a,b,0,l))return decision_log(a,"DE30"),!1;d=LP_getname(b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=d&&(0<=d.toLowerCase().indexOf("signup")||0<=d.toLowerCase().indexOf("register"))&&
-1==d.toLowerCase().indexOf("login"))return decision_log(a,"DE31",{param1:e}),formcacheset(a,e,"ask_generate",!0),!0;var h=!1;if("undefined"!=typeof Math){d=Math.floor(1E4*Math.random());var h=j=s=0,m=null,p=b.elements.length;Checkpoint.assert(p<MAX_FORM_ELEMENTS_SOFT,"form "+e+" too big 1");p>MAX_FORM_ELEMENTS_SOFT&&(p=MAX_FORM_ELEMENTS_SOFT);for(var r=0;r<p;r++){var k=b.elements[r];"INPUT"==k.tagName&&("password"==k.type?s++:("text"==k.type||"email"==k.type)&&j++);if("INPUT"==k.tagName&&"submit"==
k.type||"BUTTON"==k.tagName)if(h++,m=k,10<h&&b.elements.length>MAX_FORM_ELEMENTS_SOFT)return!1}if(1==h&&2>=j&&0<s&&checkButtonHint(m))return decision_log(a,"DE32"),!1;j=b.elements;for(r=0;r<MAX_FORM_ELEMENTS_SOFT&&r<j.length;r++)if(k=j[r],h=!1,"FIELDSET"!=k.tagName&&valid_by_role(a,k)&&!LP_fieldIsDisabled(k)&&!LP_treat_as_hidden(k)&&("expedia.com"==l||checkIsDisplayed(a,k,0,l,d)))if(!g_use_wacky_disp||is_wacky_disp(a,k)){if("text"==k.type&&is_watermark(k.className)&&is_watermark_password(k))try{k.type=
"password"}catch(t){h=!0}m=LP_elt_get_text(k);if("BUTTON"==k.tagName&&"submit"==k.type&&null!=m&&0<=m.indexOf("Create")||"BUTTON"==k.tagName&&"submit"==k.type&&null!=m&&0<=m.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Create")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Sign me up")||"INPUT"==k.tagName&&"image"==k.type&&null!=k.value&&
"create"==k.value)q=2,decision_log(a,"DE33",{param1:e});if(1<s&&LP_passwordAlt(a,k))g++;else if(m=fieldIsDoublePassword(a,k),!b||!("form1"==b.id&&b.action&&"string"==typeof b.action&&b.action.indexOf(".aspx")&&"text"==k.type&&(m===DOUBLE_PW_VISIBLE||m===DOUBLE_SECRET_PW_VISIBLE)))if(!do_bgiconinput||!("text"==k.type&&(m===DOUBLE_TEXT_VISIBLE||m===DOUBLE_SECRET_TEXT_VISIBLE))){if("password"==k.type||h||"text"==k.type&&m===DOUBLE_TEXT_VISIBLE||"text"==k.type&&m===DOUBLE_SECRET_TEXT_VISIBLE){h=k.getAttribute("placeholder");
null!=h&&0<=h.indexOf("Create your")&&(q=2);if("facebook.com"==l&&"string"==typeof k.id&&k.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/))continue;else if("tdbank.com"==l&&"string"==typeof k.name&&"user"==k.name){g++;continue}if(0==f&&1<s&&passwordIsFake(k)){g++;continue}if(0<f&&1<s&&LP_looksLikeOTPField(a,k)){g++;continue}LP_get_input_pattern(a,k)&&!c&&(c=k);f++}else if("email"==k.type||"text"==k.type||"textarea"==k.type||"tel"==k.type||"url"==k.type)if(treat_text_as_password(k))f++;else{if(LP_isForgetField(k))continue;
lpIsVisible(k,!0)&&(h=LP_pickFieldName(a,k),LP_looksLikeOTPField(a,k)?decision_log(a,"DE35",{param1:h}):g++)}if(4<=f||100<=g)return 4<=f&&decision_log(a,"DE37",{param1:e,param2:f,param3:g}),100<=g&&decision_log(a,"DE38",{param1:e,param2:f,param3:g}),formcacheset(a,e,"ask_generate",!1),!1;if(2<=f||1<=f&&g>=q)return 2<=f&&decision_log(a,"DE39",{param1:e,param2:f,param3:g}),1<=f&&g>=q&&decision_log(a,"DE40",{param1:e,param2:f,param3:g}),formcacheset(a,e,"ask_generate",!0),c&&!g_isie&&!g_isfirefox&&sendBG_generate_pattern(a,
c),!0}}decision_log(a,"DE41",{param1:e,param2:f,param3:g});formcacheset(a,e,"ask_generate",!1);return!1}}function passwordIsFake(a){var b=/(?:Account)|(?:Member)|(?:IUO_NAME)/i,d=a.name;return b.exec(a.id)||b.exec(d)?!0:!1}function checkButtonHint(a){if(!a)return!1;var b="INPUT"==a.tagName?a.value:a.innerHTML,d=/(?:Login)|(?:Log.In)|(?:Logon)|(?:Log.on)/i;return d.exec(a.id)||d.exec(b)?!0:!1}
function LP_isForgetField(a){if(!a)return!1;var b=a.id;a=a.name;var d=RegExp(lpgs("ff_forgot_regexp"),"i");return d.exec(b)||d.exec(a)?!0:!1}function LP_isCaptchaField(a){if(!a)return!1;var b=a.id;a=a.name;var d=RegExp(lpgs("ff_captcha_regexp"),"i");return d.exec(b)||d.exec(a)?!0:!1}
function element_is_detached(a,b,d){if(!b||!a&&(a=b.ownerDocument,!a))return!1;"undefined"==typeof d&&(d=0);var c=null;try{if(15<d&&(c=!1),null==b.parentNode&&(c=!0),b.parentNode===a.documentElement||b.parentNode===b.ownerDocument.documentElement)c=!1}catch(e){c=!0}return null==c?element_is_detached(a,b.parentNode,d+1):c}
function get_javaservlet_fields(a,b){if(!a)return[];if("undefined"==typeof b||null===b)b=!1;var d=[],c=a.getElementsByName("j_username"),e=a.getElementsByName("j_password");if(1===c.length&&1===e.length)Checkpoint.assert(c[0].form===e[0].form,"javaservlet form mismatch"),d=[c[0],e[0]];else if(b&&(1===c.length||1===e.length)){var f=null,j=null;1===c.length&&(f=c[0]);1===e.length&&(j=e[0]);d=[f,j]}else{c=a.getElementsByTagName("FORM");f=LP_getFormsThreshold(a);Checkpoint.assert(c.length<f,"too many forms on page");
for(e=0;e<f&&e<c.length;e++)if(c[e].action&&"undefined"!=typeof c[e].action.indexOf&&0<=c[e].action.indexOf("j_security_check")){f=form_get_username(a,c[e]);j=form_get_password(a,c[e]);f&&j&&(d=[f,j]);break}}return d}
function is_random_hashstr(a){return!a?!1:(16==a.length||32==a.length)&&a.match(/^[a-zA-Z0-9]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||32==a.length&&a.match(/^[a-f0-9]+$/)||a.match(/_\d{18}[A-Z]{4}_/)||17==a.length&&"a"==a.charAt(0)&&a.match(/^[a-zA-Z0-9_]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||(20==a.length&&a.match(/^[A-Z]0[A-F]\d{16}[A-Z]$/)||21==a.length&&a.match(/^[A-Z]0[A-F]\d{17}[A-Z]$/))||18==a.length&&a.match(/^el[0-9a-f]{16}$/)||24<a.length&&
a.match(/^yui_[0-9_]+$/)?!0:!1}function chk_form_changepw_new(){return!0}
function shouldOfferGenerate(a,b){if(null==a||null==b)return null;var d=!1,c=b.form,e=!1;c||(e=checkDocumentForCPWOrphans(a));var f=!0,j=!0,l=check_nevers(a,g_nevers,a.location.href);null!=l&&(f=l.show_for_generate,j=l.show_for_clickable_icon);if(f&&chk_form_ask_generate(a,c)&&isInputFieldPassword(a,b)&&j){if(chk_form_has_password(a,c)&&(d=LP_pickFormName(a,c),RegExp(lpgs("ff_loginform_regexp"),"i").exec(d)))return!1;(currentpw=lpCheckCurrentPWField(c))||(currentpw=lpCheckCurrentPWField(c,!0));chk_form_changepw(a,
c)&&b==lpCheckCurrentPWField(c)?(d=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE42",{param1:g_docnum,param2:LP_pickFormName(a,c),param3:LP_pickFieldName(a,b)})):chk_form_changepw_new(a,c)&&b==currentpw?(d=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE43",{param1:g_docnum,param2:LP_pickFormName(a,c),param3:LP_pickFieldName(a,b)})):(d=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE44",{param1:g_docnum,param2:LP_pickFormName(a,c),param3:LP_pickFieldName(a,b)}))}else!c&&(f&&e)&&(isInputFieldPassword(a,
elt)&&!lpIsFieldCurrentPWField(b))&&(d=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE45",{param1:g_docnum,param2:LP_pickFieldName(a,b)}));return d}function popupfill_shoulddoform(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=b.name,c=b.id,e=["lpmanualform","lpwebsiteeventform"];return d&&lp_in_array(d,e)||c&&lp_in_array(c,e)?!1:!0}
function LP_isRememberCheckbox(a){if(!a||"checkbox"!=a.type)return!1;var b=a.id;a=a.name;var d=RegExp(lpgs("ff_remember_regexp"),"i");return d.exec(b)||d.exec(a)?!0:!1}
function chk_form_is_nonlogin_form(a,b){if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;try{var d=gettldcached(a.location.href)}catch(c){return!1}var e=LP_pickFormName(a,b),f=formcacheget(a,e,"is_nonlogin");if(null!=f)return f;f="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(f.length<MAX_FORM_ELEMENTS_HARD,"form "+e+" has too many inputs");if(f.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,e,"is_nonlogin",!0),!0;if(is_search_form(a,
b))return decision_log(a,"DE46",{param1:e}),formcacheset(a,e,"is_nonlogin",!1),!1;if(!checkIsDisplayed(a,b,0,d))return decision_log(a,"DE47",{param1:e}),!1;var j=d=0,f=b.elements,l=f.length;Checkpoint.assert(l<MAX_INPUTS_HARD,"form "+e+" too big 2");l>MAX_INPUTS_HARD&&(l=MAX_INPUTS_HARD);for(var n=0;n<l;n++){var g=f[n];if("FIELDSET"!=g.tagName&&("email"==g.type||"text"==g.type||"password"==g.type)&&!LP_fieldIsDisabled(g)){if(100<++j)return formcacheset(a,e,"is_nonlogin",!1),!1;if(!0!=g.disabled&&
valid_by_role(a,g)&&lpIsVisible(g)&&!LP_treat_as_hidden(g)){if(is_search_field(a,g,!0)&&8>f.length)return decision_log(a,"DE48",{param1:e}),formcacheset(a,e,"is_nonlogin",!1),!1;d++;if(3<=d)return decision_log(a,"DE49",{param1:e}),formcacheset(a,e,"is_nonlogin",!0),!0}}}formcacheset(a,e,"is_nonlogin",!1);return!1}
function treat_text_as_password(a){return!a||"TEXTAREA"==a.tagName?!1:"text"==a.type&&(0==a.name.indexOf("pass")||0<=a.name.toLowerCase().indexOf(lpgs("Password").toLowerCase()))&&-1==a.name.toLowerCase().indexOf("hint")&&-1==a.name.toLowerCase().indexOf("placeholder")?RegExp(lpgs("ff_username_regexp"),"i").exec(a.name)&&a.form&&a.form.action&&0<=a.form.action.indexOf("login")?!1:!0:!1}function ASP_treat_text_as_password(a){return treat_text_as_password(a)}
function valid_by_role(a,b){if(!b)return!1;a||(a=b.ownerDocument);if(!a)return!1;var d=b.getAttribute("role");!d&&"INPUT"!=b.tagName&&(d=b.parentNode.getAttribute("role"));if(!d)return!0;switch(d){case "navigation":case "banner":case "contentinfo":case "note":case "search":case "seealso":return!1;case "columnheader":case "presentation":case "toolbar":case "directory":return!1;default:return!0}}
function should_do_lastpass_here(a){var b=null;if(!a)return!1;if(null!=a.g_content_check_result)return a.g_content_check_result;try{var d=a.location.href;if(0<d.indexOf(".xul")||0<d.indexOf("libsyn.com/embed")||0<d.indexOf("platform.twitter.com/tweet_button")||0<=d.indexOf("facebook.com/plugins/"))b=a.g_content_check_result=!1;null===b&&("complete"!=a.readyState&&"interactive"!=a.readyState)&&(verbose_log("answer hazy, try again later"),b=!0);if(null===b){var c=a.body,e=LP_elt_get_text(c).length;
null===b&&(2<e&&is_page_JSON(a))&&(b=a.g_content_check_result=!1)}if(null===b&&c){var f=c.getAttribute("contentEditable"),j=c.getAttribute("preview"),l=null!==c.getAttribute("data-silex-id")||null!==c.getAttribute("data-silex-type");if("edit"==j||f||l)b=!1}}catch(n){return a.g_content_check_result=!1}null===b&&(b=a.g_content_check_result=!0);return b}
function is_shopping_form(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=LP_createXPathFromElement(a,b);d||(d=LP_pickFormName(a,b));var c=formcacheget(a,d,"is-shopping");if(null!=c)return c;var c=!1,e=0,f=0,j=0,l=0,n=0,g=0,q=/qty|quantity/i,s=/[Ss]hipping/,h=/[Ss]hopping|[CcK]art/,m=/gift|Gift|GIFT/,p=/[Cc]heck[Oo]ut/,r=b.getElementsByTagName("input");Checkpoint.assert(r.length<MAX_INPUTS_SOFT,"form "+LP_getname(b)+" has too many inputs");var k=r.length;k>MAX_INPUTS_SOFT&&(k=MAX_INPUTS_SOFT);
for(g=0;g<k;g++){var t=r[g].id,u=r[g].name,v=r[g].className;if(q.exec(t)||q.exec(u)||q.exec(v))e++;else if(s.exec(t)||s.exec(u)||s.exec(v))j++;else if(h.exec(t)||h.exec(u)||h.exec(v))f++;else if(m.exec(t)||m.exec(u)||m.exec(v))l++;else if(p.exec(t)||p.exec(u)||p.exec(v))n++;else{t=void 0;u=0;v=[e,f,j,l,n];for(t=0;t<v.length;t++)0<v[t]&&u++;if(2<=u){c=!0;break}}}formcacheset(a,d,"is-shopping",c);return c}
function is_wacky_disp(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;if(b==a.body)return!0;var d=!0;try{var c=LP_get_live_style(b);if(c){if("none"==c.display||"hidden"==c.visibility)d=!1;if(!0==d&&(!b.offsetHeight||!b.offsetHeight))d=!1;if(!0==d&&(0==c.height||0==c.width))d=!1;if(!0==d&&(2>parseInt(c.height)||2>parseInt(c.width)))d=!1;if(!0==d&&(0>parseInt(c.left)&&"auto"!=c.left||0>parseInt(c.top)&&"auto"!=c.top))d=!1;!0==d&&("-1px"==c.marginTop&&1==b.offsetHeight)&&(d=!1);if(!0==d&&(3>b.offsetHeight||
3>b.offsetWidth))d=!1;if(!0==d&&("transparent"==c.backgroundColor&&"transparent"==c.color||g_isie&&"transparent"==c.backgroundColor&&""==c.color||"rgba(0, 0, 0, 0)"==c.backgroundColor&&"rgba(0, 0, 0, 0)"==c.color))d=!1;!0==d&&(c.opacity&&0.02>parseFloat(c.opacity))&&(d=!1);if(!0==d&&g_isie&&c.filter){var e=/alpha\(opacity=(\d+)\)/.exec(c.filter);e&&(e[1]&&2>parseInt(e[1]))&&(d=!1)}}}catch(f){d=!0}if(d)try{var j=b.parentNode;j||(d=!1);var l=LP_get_live_style(j);if(l){if(!0==d&&("none"==l.display||
"hidden"==l.visibility))d=!1;if(!0==d&&(0>parseInt(l.left)&&"auto"!=l.left||0>parseInt(l.top)&&"auto"!=l.top))d=!1;if(!0==d&&(3>parseInt(l.height)&&"auto"!=l.height||3>parseInt(l.width)&&"auto"!=l.width)&&("hidden"==l.overflowY||"hidden"==l.overflow))d=!1}}catch(n){d=!0}return d}
function LP_treat_as_hidden(a){return!a||"hidden"==a.type||!a.parentNode||0==a.id.indexOf("hidden")&&("none"==a.style.display||"none"==a.parentNode.style.display)||"true"===a.getAttribute("aria-hidden")?!0:(a=a.getAttribute("hidden"))&&"false"!==a?!0:!1}
function LP_has_textlike_type(a){if(!a)return!1;var b=a.tagName.toUpperCase();if("INPUT"!=b&&"TEXTAREA"!=b)return!1;if("TEXTAREA"==b)return!0;var b="text number email tel url textarea".split(" "),d;for(d in b)if(b.hasOwnProperty(d)&&a.type==b[d])return True;return False}
function computeFingerprint(a){if(!a)return"";var b="",d=a.getElementsByTagName("INPUT"),c;for(c=0;c<d.length&&20>c;c++)b+=d[c].id?d[c].id:d[c].name;a=a.getElementsByTagName("DIV");b+=a.length.toString();try{"undefined"!=typeof crc32&&(b=crc32(b).toString())}catch(e){}return b}
function LP_firstVisibleOrphan(a){if(!a)return null;a=a.getElementsByTagName("INPUT");var b,d=null;for(b=0;b<a.length&&50>b;b++)if(d=a[b],!d.form&&("text"==d.type||"password"==d.type||"url"==d.type||"email"==d.type)&&lpIsVisible(d))return d;return null}
function checkFormForLoginFirstStage(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var d=LP_pickFormName(a,b);verbose_log("checking "+d+" for first stage of multi-stage login");var c=formcacheget(a,d,"multi-first");if(null!=c)return c;if("undefined"==typeof Math)return False;for(var c=0,e=!1,f,j=Math.floor(1E4*Math.random()),l=0,n=0;20>n&&n<b.elements.length;n++)if(f=b.elements[n],"INPUT"==f.tagName&&checkIsDisplayed(a,f,0,null,j)){looksLikeUsername(f)&&c++;if("text"==f.type||"tel"==f.type||
"url"==f.type||"email"==f.type||"textarea"==f.type){if("string"==typeof f.id&&"identifier-captcha-input"==f.id)try{if("google.com"==gettldcached(a.location.href))continue}catch(g){}l++}if(isInputFieldPassword(a,f)){e=!0;break}if(2<=c)break;if(2<=l)break}if(0<c&&3>=c&&!1==e&&2>l)return verbose_log("isolated login field/initial stage of multi-stage found"),formcacheset(a,d,"multi-first",!0),!0;formcacheset(a,d,"multi-first",!1);return!1}
function checkDocumentForLoginFirstStageForm(a){if(!a)return!1;var b=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<b,"too many forms on page");for(var c=!1,e=0;e<d.length&&e<b;e++)if(c=checkFormForLoginFirstStage(a,d[e]))return c;return!1}
function checkDocumentForNonLoginOrphans(a){if(null==a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup"),d=formcacheget(a,"fakedoc","orphan-registration"),c=formcacheget(a,"fakedoc","orphan-cc"),b=b||d||c;if(null!=b)return b;b=RegExp(lpgs("ff_firstname_regexp"),"i");d=RegExp(lpgs("ff_lastname_regexp"),"i");c=RegExp(lpgs("ff_cctype_regexp"),"i");lpgs("ff_address1_regexp");lpgs("ff_forgot_regexp");lpgs("ff_remember_regexp");var e=!1,f=!1,j=!1,l=!1,n=!1;try{gettldcached(a.location.href)}catch(g){return!1}for(var q=
0,s=a.getElementsByTagName("INPUT"),h=0;h<s.length&&20>h;h++){var m=s[h];if("INPUT"==m.tagName){LP_isRememberCheckbox(m)&&(lpIsVisible(m)&&!LP_fieldIsDisabled(m))&&q++;if("email"==m.type||"text"==m.type||"password"==m.type){if(LP_fieldIsDisabled(m))continue;if(LP_fieldIsDisabled(m))continue;if(!valid_by_role(a,m))continue;if(!lpIsVisible(m))continue;if(is_search_field(a,m,!0))continue;var p=m.name,r=m.id?m.id:"",k=lpGetTextBeforeFormField(m);looksLikeUsername(m)?e=!0:isInputFieldPassword(a,m)?f=!0:
b.exec(r)||b.exec(p)||b.exec(k)?j=!0:d.exec(r)||d.exec(p)||d.exec(k)?l=!0:c.exec(r)||c.exec(p)||c.exec(k)?n=!0:regexp_address1.exec(r)||regexp_address1.exec(p)||regexp_address1.exec(k);q++}if(3<=q){if(e&&f&&!n)return verbose_log("document appears to be have orphan signup fields"),formcacheset(a,"fakedoc","orphan-signup",!0),formcacheset(a,"fakedoc","orphan-cc",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if(n&&!e&&!f)return verbose_log("document appears to be have orphan credit card fields"),
formcacheset(a,"fakedoc","orphan-cc",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if((j||l)&&e)return verbose_log("document appears to be have orphan registration fields"),formcacheset(a,"fakedoc","orphan-registration",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-cc",!1),!0}}}formcacheset(a,"fakedoc","orphan-signup",!1);formcacheset(a,"fakedoc","orphan-cc",!1);formcacheset(a,"fakedoc","orphan-registration",
!1);return!1}function checkDocumentHasOrphanSignup(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-signup")}function checkDocumentHasOrphanCC(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-cc");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-cc")}
function checkDocumentHasOrphanRegistration(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-registration");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-registration")}
function LP_should_ignore_this_doc(a){if(!a||!a.location)return!0;a=a.location.href;return 0==a.indexOf("chrome:")||(0==a.indexOf("chrome-extension://")||0==a.indexOf("safari-extension://")||0==a.indexOf("moz-extension://")||0==a.indexOf("about:")||0==a.indexOf("javascript:")||0==a.indexOf("resource:"))||0<a.indexOf(".xul")?!0:!1}
function countInputs(a,b,d){var c=0,e=0,f=a.getElementsByTagName("INPUT");if("undefined"!=typeof Math){for(var j=0;j<f.length;j++){if(100<j){b||(c+=f.length-j);break}var l="password"==f[j].type;if(!b||l)"checkbox"==f[j].type||"hidden"==f[j].type||(l&&e++,c++)}d&&(a.g_password_cnt=e);return c}}
function checkForLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(b){return!1}var d=LP_getFormsThreshold(a),c=a.getElementsByTagName("form");Checkpoint.assert(c.length<d,"too many forms on page");for(var e=!1,f=0;f<c.length&&f<d;f++){e=chk_form_has_password(a,c[f],!0);if(null==e)break;if(e)return e}return!1}
function checkForNonLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(b){return!1}var d=LP_getFormsThreshold(a),c=a.getElementsByTagName("form");Checkpoint.assert(c.length<d,"too many forms on page");for(var e=!1,f=0;f<c.length&&f<d;f++)if(e=chk_form_is_nonlogin_form(a,c[f]))return e;return!1}
function checkForSignupForm(a){a||(a=LP_derive_doc());if(!a)return!1;var b=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<b,"too many forms on page");for(var c=!1,e=0;e<d.length&&e<b;e++)if(c=chk_form_ask_generate(a,d[e]))return c;return!1}
function chk_form_has_password(a,b,d){if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;var c=LP_pickFormName(a,b),e=formcacheget(a,c,"is_login");if(null!=e)return e;e="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(e.length<MAX_FORM_ELEMENTS_HARD,"form "+c+" has too many inputs");if(e.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,c,"is_login",!1),!1;try{var f=gettldcached(a.location.href);if("bankofamerica.com"==f){var j=
a.getElementById("tlpvt-passcode-input");null!==j&&j.removeAttr("disabled")}}catch(l){return!1}for(var n=!1,g=j=0,q=0,e=null,s=0;s<MAX_FORM_ELEMENTS_SOFT&&s<b.elements.length;s++){var h=b.elements[s];"INPUT"==h.tagName&&("password"==h.type?j++:("text"==h.type||"email"==h.type)&&g++);if("INPUT"==h.tagName&&"submit"==h.type||"BUTTON"==h.tagName)q++,e=h}verbose_log("check for login form: prelimtxt="+g+" prelimpw="+j);if(1==q&&2>=g&&0<j&&checkButtonHint(e))return!0;for(var m=0,p=0,r=!lpIsVisible(b),k=
!1,e=b.elements,s=0;s<MAX_FORM_ELEMENTS_SOFT&&s<e.length;s++)if(h=e[s],n=!1,"FIELDSET"!=h.tagName&&(check_for_ASP(a,h),valid_by_role(a,h)&&!LP_fieldIsDisabled(h)&&!LP_treat_as_hidden(h))){if("text"==h.type&&is_watermark(h.className)&&is_watermark_password(h))try{h.type="password",decision_log(a,"DE11")}catch(t){n=!0}ASP_treat_text_as_password(h)&&(n=!0);(n||"password"==h.type)&&LP_get_input_pattern(a,h);if(1<j&&LP_passwordAlt(a,h))p++;else if(b=fieldIsDoublePassword(a,h),!("text"==h.type&&(b===DOUBLE_PW_VISIBLE||
b===DOUBLE_SECRET_PW_VISIBLE)))if("password"==h.type||n||"text"==h.type&&b===DOUBLE_TEXT_VISIBLE||"text"==h.type&&b===DOUBLE_SECRET_TEXT_VISIBLE){if(!("facebook.com"==f&&"string"==typeof h.id&&h.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/)))if("tdbank.com"==f&&"string"==typeof h.name&&"user"==h.name)p++;else{if(g_fillaid&&d)return!0;if(g_aspx_hack&&isASPpage()&&do_bgiconinput)decision_log(a,"DE12");else if(!lpIsVisible(h)||g_use_wacky_disp&&!is_wacky_disp(a,h))if(k=!0,r)decision_log(a,"DE13",{param1:LP_pickFormName(a,
h)});else continue;if(0==m&&1<j&&passwordIsFake(h))p++;else if(0<m&&1<j&&LP_looksLikeOTPField(a,h))p++;else if(b=2,h="",g_aspx_hack&&(isASPpage()&&do_bgiconinput)&&(b=4,h=" [ASP]"),++m>=b){if(2==j&&(0===g&&1===q)&&RegExp(lpgs("ff_loginform_regexp"),"i").exec(c))return formcacheset(a,c,"is_login",!0),!0;formcacheset(a,c,"is_login",!1);verbose_log("Password Form detection: "+c+h+" has too many password fields; do not treat as login form [PW:"+m+"/NON:"+p+"]");return null}}}else if("email"==h.type||
"text"==h.type||"textarea"==h.type||"tel"==h.type||"url"==h.type){if(!lpIsVisible(h)||g_use_wacky_disp&&!is_wacky_disp(a,h))if(r)verbose_log("EVALUATING HIDDEN FORM, NOT IGNORING HIDDEN FIELD ANYMORE "+LP_pickFormName(a,h));else continue;p++;if(g_aspx_hack&&5<p||!g_aspx_hack&&2<p)return formcacheset(a,c,"is_login",!1),verbose_log("Password Form detection: "+c+" has too many non-password fields; do not treat as login form [PW:"+m+"/NON:"+p+"]"),null}}if(1==m)return verbose_log("Password Form detection: "+
c+" is a login form, has only one passwd field"),formcacheset(a,c,"is_login",!0),!0;if(g_aspx_hack&&(isASPpage()&&do_bgiconinput)&&1<m)return verbose_log("Password Form detection: "+c+" is an ASP form, treat as login form"),formcacheset(a,c,"is_login",!0),!0;k||formcacheset(a,c,"is_login",!1);return!1}function looksLikePassword(a,b){return isInputFieldPassword(a,b)}
function isInputFieldPassword(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"hidden"==b.type)return!1;try{var d=gettldcached(a.location.href)}catch(c){return!1}if(!valid_by_role(a,b))return!1;var e=!1;if("text"==b.type&&is_watermark(b.className)&&is_watermark_password(b))try{b.type="password"}catch(f){e=!0}if("text"==b.type&&(0==b.name.indexOf("pass")||0==b.name.toLowerCase().indexOf(lpgs("Password").toLowerCase())))return RegExp(lpgs("ff_username_regexp"),"i").exec(b.name)&&b.form&&b.form.action&&
0<=b.form.action.indexOf("login")?!1:!0;g_aspx_hack&&isASPpage()&&do_bgiconinput&&"text"==b.type&&0<=b.value.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&(e=!0);return"password"==b.type||e?"facebook.com"==d&&"string"==typeof b.id&&b.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/)||"tdbank.com"==d&&"string"==typeof b.name&&"user"==b.name||"google.com"==d&&"string"==typeof b.id&&"Passwd-hidden"==b.id?!1:!0:!1}
function checkDocumentForLoginOrphans(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan");if(null!=b)return b;var b=[],d=[],c=[],e=0,f,j=0;if("undefined"!=typeof Math){for(var l=Math.floor(1E4*Math.random()),n=["input"],g=0;g<n.length;g++){var q=a.getElementsByTagName(n[g]),s=q.length;Checkpoint.assert(s<MAX_INPUTS_SOFT,"page has too many inputs");s>MAX_INPUTS_SOFT&&(s=MAX_INPUTS_SOFT);for(var h=0;h<s;h++)if(checkIsDisplayed(a,q[h],0,null,l)){f=q[h];if(null!=f.id&&""!=
f.id){var m=c[f.id];if(null==m)c[f.id]=!0;else continue}if(null!=f.name&&""!=f.name)if(m=d[f.name],null==m)d[f.name]=!0;else continue;if(lp_in_array(LP_pickFieldName(a,f),b))verbose_log("fieldname "+b[m]+" is blacklisted, skipping");else{var p=fieldIsDoublePassword(a,f);if(null==f.form&&("password"==f.type||"text"==f.type&&p===DOUBLE_TEXT_VISIBLE||"text"==f.type&&p===DOUBLE_SECRET_TEXT_VISIBLE)){e++;var p=[],r;r=LP_pickFieldName(a,f);f=LP_getname(f);r&&p.push(r);f&&r!=f&&p.push(f);for(f=0;f<p.length;f++)if((r=
p[f])&&0<=r.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&0<h){var k=q[h-1];r=LP_pickFieldName(a,k);var k=LP_getname(k),t=RegExp(lpgs("ff_username_regexp"),"i");if(t.exec(r)||t.exec(k)){j++;break}}}if(2<=e&&2<=j)break}}}if(1<=e||1==j)return formcacheset(a,"fakedoc","orphan",!0),!0;formcacheset(a,"fakedoc","orphan",!1);return!1}}
function chk_form_changepw(a,b){if(null==a||null==b)return!1;for(var d=lpCheckCurrentPWField(b),c=!1,e=null,f=null,j=1;2>=j;j++){var c=!1,e=f=null,l=-1;if(1==j){if(d)for(var n=0;n<b.elements.length;n++)if(b.elements[n]==d){l=n+1;break}}else l=0;if(-1!=l){for(n=l;n<b.elements.length;n++)if(l=b.elements[n],"FIELDSET"!=l.tagName)if(isInputFieldPassword(a,l)){if(c||!e||!f)if(f=e,e=l,c&&e&&f)break;c=!0}else c=!1;if(e&&f)break}}return null!=e&&null!=f&&null!=d?!0:!1}
function form_get_password(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var d=LP_pickFormName(a,b),c=formcacheget(a,d,"password_field");if(null!==c)return c;if(!0===formcacheget(a,d,"nopasswords"))return null;var c=null,e,f=[],f="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==f&&0<f.length,"empty form?");if("undefined"==typeof Math)return null;var j=f.length;Checkpoint.assert(j<MAX_FORM_ELEMENTS_HARD,"form "+d+" too big 3");j>MAX_FORM_ELEMENTS_HARD&&
(j=MAX_FORM_ELEMENTS_HARD);var l=0;for(e=0;e<j;e++)isInputFieldPassword(a,f[e])&&l++;e=Math.floor(1E4*Math.random());for(var n=0;n<j;n++){var g=f[n];if("FIELDSET"!=g.tagName&&(checkIsDisplayed(a,g,0,null,e)&&isInputFieldPassword(a,g))&&!(1<l&&(passwordIsFake(g)||LP_looksLikeOTPField(a,g)||!valid_by_role(a,g)||LP_fieldIsDisabled(g)||LP_treat_as_hidden(g)||is_search_field(a,g,!0)))){c=g;break}}null===c&&0===l&&formcacheset(a,d,"nopasswords",!0);formcacheset(a,d,"password_field",c);return c}
function form_get_username(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var d=[],d="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==d);var c=null,e=LP_pickFormName(a,b),f=formcacheget(a,e,"username_field");if(null!==f)return f;if("undefined"==typeof Math)return null;f=d.length;Checkpoint.assert(f<MAX_FORM_ELEMENTS_HARD,"form "+e+" too big 4 ");f>MAX_FORM_ELEMENTS_HARD&&(f=MAX_FORM_ELEMENTS_HARD);for(var j=Math.floor(1E4*Math.random()),l=0;l<
f;l++){var n=d[l];if(!("FIELDSET"==n.tagName||"hidden"==n.type))if(valid_by_role(a,n)&&!LP_fieldIsDisabled(n)&&!is_search_field(a,n,!0)&&checkIsDisplayed(a,n,0,null,j)&&("text"==n.type||"email"==n.type||looksLikeUsername(n))){if(isFirstFieldNonLoginSubForm(a,n))return null;c=n;break}}formcacheset(a,e,"username_field",c);return c}
function doc_get_orphan_username(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b;if("undefined"!=typeof Math){b=formcacheget(a,"orphans","username_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[0])return formcacheset(a,"orphans","username_field",b[0]),b[0];var d=doc_get_form_equivalents(a);if(d&&0<d.length)for(b=0;b<d.length;b++){var c=form_get_username(a,d[b]);if(c)return formcacheset(a,"orphans","username_field",c),c}formcacheset(a,
"orphans","username_field","none");return null}}
function doc_get_orphan_password(a){if(null==a)return null;if("undefined"!=typeof Math){var b=formcacheget(a,"orphans","password_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[1])return formcacheset(a,"orphans","password_field",b[1]),b[1];if((b=doc_get_form_equivalents(a))&&0<b.length)for(x=0;x<b.length;x++){var d=form_get_password(a,b[x]);if(d)return formcacheset(a,"orphans","password_field",d),d}formcacheset(a,"orphans","password_field",
"none");return null}}function set_active_username_password(a,b){if(null==a)g_popup_active_password=g_popup_active_username=null;else{var d=null,c=null;null==b?checkDocumentForLoginOrphans(a)&&(d=doc_get_orphan_username(a),c=doc_get_orphan_password(a)):(d=form_get_username(a,b),c=form_get_password(a,b));g_popup_active_username=d;g_popup_active_password=c}}
function looksLikeEmail(a,b){return null==a||null==b||!("text"==b.type||"email"==b.type)?!1:"email"==b.type||RegExp(lpgs("ff_email_regexp"),"i").exec(b.name)?!0:!1}
function is_search_field(a,b,d){if(null==a||null==b||"INPUT"!=b.tagName.toUpperCase()&&!b.getAttribute("contentEditable"))return!1;var c=null;switch(b.type){case "search":c=!0;break;case "text":break;default:"INPUT"==b.tagName.toUpperCase()&&(c=!1)}if(null!==c)return c;null===d&&(d=!1);var c=LP_pickFieldName(a,b),e=fieldcacheget(a,c,"search");if(null!=e)return e;var e=b.form,f=[];null!=e&&(f=e.elements);if(b.parentNode&&"FORM"!=b.parentNode.tagName&&b.parentNode.className&&0<=b.parentNode.className.toLowerCase().indexOf("login")&&
b.className&&0<=b.className.toLowerCase().indexOf("search"))return!1;if((null!=b.className&&0<=b.className.toLowerCase().indexOf("search")||0<=b.className.toLowerCase().indexOf("srch")||0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch")||0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch"))&&0>b.name.toLowerCase().indexOf("user")&&0>b.name.toLowerCase().indexOf("login")&&0>b.id.toLowerCase().indexOf("user")&&0>b.id.toLowerCase().indexOf("login")&&
(d||5>f.length))return fieldcacheset(a,c,"search",!0),!0;d=RegExp(lpgs("ff_search_regexp"),"i");if(d.exec(b.name)||d.exec(b.id))if(d=b.name&&b.name.match(/[qQ]/)||b.id&&b.id.match(/[qQ]/),e=RegExp(lpgs("ff_email_regexp"),"i"),f=RegExp(lpgs("ff_username_regexp"),"i"),d&&b.name&&!b.name.match(/^[qQ]/)&&(!b.id||b.id&&!b.id.match(/^[qQ]/)))pass;else if(d&&b.id&&!b.id.match(/^[qQ]/)&&(!b.name||b.name&&!b.name.match(/^[qQ]/)))pass;else if(d&&(f.exec(b.name)||f.exec(b.id)||e.exec(b.name)||e.exec(b.id)))pass;
else return verbose_log("field "+c+" appears to be a search field based on regexp"),fieldcacheset(a,c,"search",!0),!0;d=b.getAttribute("placeholder");if(null!=d&&0<=d.toLowerCase().indexOf("search"))return verbose_log("field "+c+" appears to be a search field based on placeholder text"),fieldcacheset(a,c,"search",!0),True;if("rds-instances-filter-txtbx"==b.id)return verbose_log("field "+c+" appears to be a search field based on manually added searchtext"),fieldcacheset(a,c,"search",!0),!0;if(b.parentNode&&
"FORM"!=b.parentNode.tagName&&b.parentNode.className&&(0<=b.parentNode.className.toLowerCase().indexOf("search")||0<=b.parentNode.className.toLowerCase().indexOf("srch"))||"search"==b.getAttribute("role"))return fieldcacheset(a,c,"search",!0),!0;d=b.getAttribute("spellcheck");if(b.className&&0<=b.className.indexOf("tt-input")&&d&&"false"===d)return fieldcacheset(a,c,"search",!0),!0;fieldcacheset(a,c,"search",!1);return!1}
function is_date_field(a){if(!a)return!1;var b=a.name,d=/(?:date)|(?:calendar)/i,c=/(?:validate)/i,b=a.name,e=a.id,f=a.className;if(d.exec(b)||d.exec(e)||d.exec(f))return c.exec(b)||c.exec(e)||c.exec(f)?!1:!0;if(a=a.getAttribute("placeholder"))if(a=a.toLowerCase(),-1!=a.indexOf("yyyy")||-1!=a.indexOf("/yy")||-1!=a.indexOf("mm/"))return!0;return!1}
function is_search_form(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var d=LP_pickFormName(a,b),c=formcacheget(a,d,"search");if(null!=c)return c;if(null!=b.id&&0<b.id.length&&"undefined"!=typeof b.id.toLowerCase&&(0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch"))||null!=b.name&&0<b.name.length&&"undefined"!=typeof b.name.toLowerCase&&(0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch")))return verbose_log("form "+d+" appears to be a search form based on name/id "),
formcacheset(a,d,"search",!0),!0;if("search"==b.getAttribute("role"))return formcacheset(a,d,"search",!0),!0;formcacheset(a,d,"search",!1);return!1}
function looksLikeUsername(a,b){if(!a)return!1;var d=LP_hasAngular(a.ownerDocument,a);if("undefined"==typeof b||null===b)b=!1;if(!b&&"text"!=a.type&&"email"!=a.type&&"url"!=a.type)return!1;var c=RegExp(lpgs("ff_username_regexp"),"i");if(c.exec(a.name)||a.id&&c.exec(a.id))return!0;var e=a.getAttribute("placeholder");if(null!=e&&0<=e.indexOf("Login")||d&&(d=LP_getAngularAttributes(a))&&d["ng-model"]&&c.exec(d["ng-model"]))return!0;d=RegExp(lpgs("ff_loginform_regexp"),"i");if(a.form)for(var e=a.form.elements,
f=0;f<e.length;f++)if("submit"==e[f].type&&(e[f].name&&c.exec(e[f].name)||d.exec(e[f].name)))return!0;c=/^id$|.*-id|online.*id$|.*Id$|onlineId\d?$/i;if(c.exec(a.name))return!0;if(g_is_specialsite){c=RegExp(lpgs("ff_bankacctnum_regexp"),"i");if(c.exec(a.name))return!0;c=RegExp(lpgs("ff_company_regexp"),"i");if(c.exec(a.name))return!0;c=RegExp(lpgs("ff_email_regexp"),"i");if(c.exec(a.name))return!0}return!1}
function formHasUsernameField(a){if(a=a.form){a=a.elements;for(var b=0;b<a.length;b++){var d=a[b];if("text"==d.type||"email"==d.type)return!0}}return!1}var DOUBLE_TEXT_VISIBLE=1,DOUBLE_PW_VISIBLE=2,DOUBLE_SECRET_TEXT_VISIBLE=3,DOUBLE_SECRET_PW_VISIBLE=4,NOT_DOUBLE_PW=0;
function fieldIsDoublePassword(a,b){"document"==a&&(a=document,b=LP_getElementByIdOrName(a,b));if(null==a&&(a=document,!a))return!1;if(null==b||"checkbox"==b.type||"button"==b.type||"submit"==b.type||"select-one"==b.type)return NOT_DOUBLE_PW;var d=null,c=null,e=null,f=null;if("undefined"!=typeof b.previousElementSibling)d=b.previousElementSibling;else if((d=b.previousSibling)&&null!=d.nodeType&&3==d.nodeType)d=d.previousSibling;if("undefined"!=typeof b.nextElementSibling)c=b.nextElementSibling;else if((c=
b.nextSibling)&&null!=c.nodeType&&3==c.nodeType)c=c.nextSibling;d&&"INPUT"!=d.tagName&&(d=null);c&&"INPUT"!=c.tagName&&(c=null);if(d){if("undefined"!=typeof d.previousElementSibling)e=d.previousElementSibling;else if((e=d.previousSibling)&&null!=e.nodeType&&3==e.nodeType)e=e.previousSibling;e&&"INPUT"!=e.tagName&&(e=null)}if(c){if("undefined"!=typeof c.nextElementSibling)f=c.nextElementSibling;else if((f=c.nextSibling)&&null!=f.nodeType&&3==f.nodeType)f=f.nextSibling;f&&"INPUT"!=f.tagName&&(f=null)}if("undefined"!=
typeof Math){var j=Math.floor(1E4*Math.random());if("password"==b.type&&!checkIsDisplayed(a,b,-1,null,j)&&d&&"text"==d.type&&!checkIsDisplayed(a,d,-1,null,j)&&c&&"text"==c.type&&checkIsDisplayed(a,c,-1,null,j)&&f&&"text"==f.type&&checkIsDisplayed(a,f,-1,null,j)||"text"==b.type&&checkIsDisplayed(a,b,-1,null,j)&&d&&"text"==d.type&&checkIsDisplayed(a,d,-1,null,j)&&e&&"password"==e.type&&!checkIsDisplayed(a,e,-1,null,j))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double secret password hack"),
g_double_secret_password_hack=!0,DOUBLE_SECRET_TEXT_VISIBLE;if("password"==b.type&&checkIsDisplayed(a,b,-1,null,j)&&d&&"text"==d.type&&!checkIsDisplayed(a,d,-1,null,j)||"text"==b.type&&!checkIsDisplayed(a,b,-1,null,j)&&c&&"password"==c.type&&checkIsDisplayed(a,c,-1,null,j))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE;var e=null!=b&&lpIsVisible(b,!0),f=null!=d&&lpIsVisible(d,!0),j=null!=c&&lpIsVisible(c,!0),l=null!=b&&
looksLikeUsername(b),n=null!=d&&looksLikeUsername(d),g=null!=c&&looksLikeUsername(c);return"password"==b.type&&!e&&d&&"text"==d.type&&f&&!n||"text"==b.type&&e&&!l&&c&&"password"==c.type&&!j||"password"==b.type&&!e&&c&&"text"==c.type&&j&&!g||"text"==b.type&&e&&!l&&d&&"password"==d.type&&!f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_TEXT_VISIBLE):"password"==b.type&&e&&d&&"text"==d.type&&!f&&!n||"text"==b.type&&!e&&c&&"password"==c.type&&
j||"password"==b.type&&e&&c&&"text"==c.type&&!j&&!g||"text"==b.type&&!e&&d&&"password"==d.type&&f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE):NOT_DOUBLE_PW}}
function ContigPWHack(a,b,d){null===a&&(a=document);if(null===a||"undefined"==typeof a.getElementsByTagName)return!1;var c=lpCountInputFields(b);if("undefined"!=typeof Math){b=Math.floor(1E4*Math.random());if((3==c.passwordvisible||4==c.passwordvisible)&&!0===c.passwordsContiguous)for(var e=a.getElementsByTagName("input"),c=0;c<e.length&&!(100<c);c++)if(e[c]==d){if("undefined"!=typeof e[c+1]&&"password"==e[c+1].type&&"undefined"!=typeof e[c+2]&&"password"==e[c+2].type&&checkIsDisplayed(a,e[c],-1,
null,b)&&checkIsDisplayed(a,e[c+1],-1,null,b)&&checkIsDisplayed(a,e[c+2],-1,null,b))return!0;break}return!1}}
function isContigPW(a,b,d){null==b&&(b=a);var c=b.getElementsByTagName("input");if("undefined"!=typeof Math){var e=Math.floor(1E4*Math.random());for(b=0;b<c.length;b++)if(c[b]==d&&"password"==c[b].type){if("undefined"!=typeof c[b+1]&&"password"==c[b+1].type&&checkIsDisplayed(a,c[b],-1,null,e)&&checkIsDisplayed(a,c[b+1],-1,null,e)||"undefined"!=typeof c[b-1]&&"password"==c[b-1].type&&checkIsDisplayed(a,c[b],-1,null,e)&&checkIsDisplayed(a,c[b-1],-1,null,e))return!0;break}return!1}}
function get_prev_field(a,b){if("undefined"!=typeof b.previousElementSibling)prev_field=b.previousElementSibling;else if((prev_field=b.previousSibling)&&null!=prev_field.nodeType&&prev_field.nodeType==TEXT_NODE)prev_field=prev_field.previousSibling}function get_next_field(a,b){if("undefined"!=typeof b.nextElementSibling)next_field=b.nextElementSibling;else if((next_field=b.nextSibling)&&null!=next_field.nodeType&&next_field.nodeType==TEXT_NODE)next_field=next_field.nextSibling}
function isFirstFieldNonLoginSubForm(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type)return!1;if("text"==b.type){var d=RegExp(lpgs("ff_firstname_regexp"),"i");if(d.exec(b.name)||d.exec(b.id))return!0;d=/register|signup|enroll|create/i;if(b.parentNode&&d.exec(b.parentNode.name)||d.exec(b.parentNode.id)||b.parentNode&&b.parentNode.parentNode&&(d.exec(b.parentNode.parentNode.name)||d.exec(b.parentNode.parentNode.id)))return!0}return!1}
function isUsernameFieldLoginSubForm(a,b){return null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type?!1:FoundNonLoginSubForm(a)?False:looksLikeUsername(b)?!0:!1}function FoundNonLoginSubForm(a){if(null==a)return!1;if(isASPpage()){a=getAllIconStates();var b;for(b=0;b<a.length;b++)if("formfills"==a[b].fillhint)return True}return False}
function isPasswordFieldLoginSubForm(a,b){if(null==a||(null==b||"INPUT"!=b.tagName)||"hidden"==b.type)return!1;if(FoundNonLoginSubForm(a))return False;if("password"==b.type){var d=a.getElementsByTagName("INPUT"),c;for(c=0;c<d.length&&c<MAX_INPUTS_HARD&&b!=d[c];c++);if(b==d[c]&&0<c){var e=LP_pickFieldName(a,b);if(e&&e.toLowerCase().indexOf(0<=lpgs("Password"))&&(d=LP_pickFieldName(a,d[c-1]),RegExp(lpgs("ff_username_regexp"),"i").exec(d)))return!0}}return!1}
function isASPpage(){var a=!1;if(g_isfirefox){var b;(b="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?a=b.g_found_aspx:verbose_log("unable to get g_found_aspx in isASPpage() for "+b?b.location.href:"null")}else a=g_found_aspx;a||(a=!1);return a}
function setASPpage(a){null==a&&(a=!0);if(g_isfirefox){var b;(b="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?ret=b.g_found_aspx=a:verbose_log("unable to set g_found_aspx in isASPpage() for "+b?b.location.href:"null")}else g_found_aspx=a,ret=!0;ret||(ret=!1);return ret}
function checkDocumentForLoginOrphansFirstStage(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-first");if(null!=b)return b;if("undefined"!=typeof Math){for(var b=[],d=[],c=0,e=!1,f=Math.floor(1E4*Math.random()),j=["input"],l=0;l<j.length;l++)for(var n=a.getElementsByTagName(j[l]),g=0;g<n.length;g++){var q=n[g];if(20<g)break;if(!n[g].form&&checkIsDisplayed(a,n[g],0,null,f)){verbose_log("checking "+LP_pickFieldName(a,q));if(null!=q.id&&""!=q.id){var s=d[q.id];if(null==s)d[q.id]=!0;else continue}if(null!=
q.name&&""!=q.name)if(s=b[q.name],null==s)b[q.name]=!0;else continue;looksLikeUsername(q)&&c++;if(isInputFieldPassword(a,q)){e=!0;break}if(2<c)break}}if(0<c&&4>=c&&!1==e)return decision_log(a,"DE27"),formcacheset(a,"fakedoc","orphan-first",!0),!0;formcacheset(a,"fakedoc","orphan-first",!1);return!1}}
function LP_looksLikeOTPField(a,b){if(!a||!b||"INPUT"!=b.tagName)return!1;if(LP_pickFieldName(a,b).toLowerCase().match(/^otp[_\W]|[_\W]otp$|^otp$|[_\W]otp[_\W]/))return!0;var d=b.getAttribute("aria-label");return d&&0<d.indexOf("O-Key")?!0:!1}function LP_fieldIsDisabled(a){return!a?!1:"undefined"!=typeof a.disabled&&a.disabled||"true"===a.getAttribute("aria-disabled")?!0:!1}
function LP_fieldIsReadOnly(a){return!a?!1:"undefined"!=typeof a.readOnly&&a.readOnly||"true"===a.getAttribute("aria-readonly")?!0:!1}function LP_fieldIsDecorative(a){return!a?!1:"presentation"===a.getAttribute("role")?!0:!1}
function checkDocumentForCPWOrphans(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b=formcacheget(a,"fakedoc","cpw");if(null!=b)return b;var b=null,d=0,c=a.getElementsByTagName("INPUT");Checkpoint.assert(c.length<=MAX_INPUTS_HARD,"page has too many inputs");for(var e=0;e<c.length;e++){var f=c[e];if(e>MAX_INPUTS_HARD)break;if(null==f.form){if(isInputFieldPassword(a,f)&&lpIsVisible(f)&&(d++,f=lpIsFieldCurrentPWField(f))){if(b)return!1;b=f}if(4<=d)return formcacheset(a,"fakedoc","cpw",!1),!1}}if(2<=
d&&b)return formcacheset(a,"fakedoc","cpw",!0),!0;formcacheset(a,"fakedoc","cpw",!1);return!1}
function ForceFillFieldClicked(a,b,d,c){if(!b||!c)return!1;d=b.form&&!d?LP_getname(b.form):"";var e=b.type?b.type:"";return"password"==e?LP_getname(b)?LP_setval(a,LP_getname(b),c.p,0,c.a,d,e,c.sharedsite,null,c.automaticallyFill,c.reqinfo,null,!0,c.humanize,c.reqinfo,c.realurl):LP_fill_given_field(a,b,c.p,e,c.sharedsite,c.automaticallyFill,c.a,!0,!0,c.humanize,c.reqinfo,c.realurl):""==c.u?!0:LP_getname(b)?LP_setval(a,LP_getname(b),c.u,0,c.a,d,e,c.sharedsite,null,c.automaticallyFill,c.reqinfo,null,
!0,c.humanize,c.reqinfo,c.realurl):LP_fill_given_field(a,b,c.u,e,c.sharedsite,c.automaticallyFill,c.a,!0,!0,c.humanize,c.reqinfo,c.realurl)}function ForceFillFormClicked(a,b,d,c){if(!b)return!1;d=null;if(b=b.getElementsByTagName("INPUT")){if(d=GuessUserPassFields(b,!0,!0,!0))d.text&&ForceFillFieldClicked(a,d.text,!1,c),d.password&&ForceFillFieldClicked(a,d.password,!1,c);return!0}return!1}
function GuessUserPassFields(a,b,d,c){if(!a||0>=a.length)return null;var e,f=a.length,j=null,l=null,n=!1;for(e=0;e<f;e++){var g=a[e];if(g)if(d&&(LP_fieldIsReadOnly(g)||LP_fieldIsDisabled(g)))decision_log(document,"DE24");else if(c&&!lpIsVisible(g,!0))decision_log(document,"DE25");else{if(b){var q=RegExp(lpgs("ff_search_regexp"),"i");if(q.exec(g.name)||q.exec(g.id)){var q=g.name&&g.name.match(/[qQ]/)||g.id&&g.id.match(/[qQ]/),s=RegExp(lpgs("ff_username_regexp"),"i"),h=RegExp(lpgs("ff_email_regexp"),
"i");if(q&&g.name&&!g.name.match(/^[qQ]/)&&(!g.id||g.id&&!g.id.match(/^[qQ]/)))pass;else if(q&&g.id&&!g.id.match(/^[qQ]/)&&(!g.name||g.name&&!g.name.match(/^[qQ]/)))pass;else if(q&&(s.exec(g.name)||s.exec(g.id)||h.exec(g.name)||h.exec(g.id)))pass;else{decision_log(document,"DE23");continue}}}if(("text"==g.type||"tel"==g.type||"email"==g.type)&&!l)b?(q=RegExp(lpgs("ff_username_regexp"),"i"),q.exec(g.name)||q.exec(g.id)?(j=g,n=!0):n||(j=g)):j=g;"password"==g.type&&!l&&(b?(q=RegExp(lpgs("ff_username_regexp"),
"i"),!n&&(q.exec(g.name)||q.exec(g.id))?j=g:l=g):l=g)}}a={};j&&(a.text=j);l&&(a.password=l);return isEmptyObject(a)?null:a}
function ForceFillClicked(a,b,d){var c=g_popupfill_parent;c||(c=g_popupfill_parent_last);if(!c){if(g_force_fill_active_element){var e=LP_getActiveElement(a);e&&("INPUT"==e.tagName&&LP_docHasFocus(a)&&hasIconState(a,LP_pickFieldName(a,e)))&&(c=e,info_log("CV21"))}if(!c)return!1}if(!a&&(a=c.ownerDocument,!a))return!1;var e=chk_form_has_password(a,c.form),f=chk_form_ask_generate(a,c.form);return c.form&&e&&!f?!ForceFillFormClicked(a,c.form,b,d)||""===c.value?ForceFillFieldClicked(a,c,b,d):!0:null==c.form?
ForceFillOrphanFieldClicked(a,c,d):ForceFillFieldClicked(a,c,b,d)}function isMultiStageLoginForm(){}function LP_passwordAlt(a,b){return!a||!b||"INPUT"!=b.tagName?!1:"nyckel"==LP_pickFieldName(a,b).toLowerCase()&&"password"==b.type?!0:!1}
function LP_explicit_ignored(a,b){if(!a||!b||"undefined"==typeof b.getAttribute)return!0;var d=b.getAttribute("data-lpignore");if("true"===d)return!0;d=b.dataset?b.dataset.lpignore:!1;if("true"===d)return!0;d=b.getAttribute("lpignore");return"true"===d||"true"===b.lpignore?!0:!1}function countFormEquivalents(a){var b=0,d=a.getElementsByTagName("FORM");a=LP_getFormsThreshold(a);for(var c=0;c<d.length&&c<a;c++)(lpIsVisible(d[c]),!0)&&b++;return b}
function LP_implicit_ignored(a,b){if(!b||!a&&(a=LP_derive_doc(),!a))return!1;var d=b.id,c=b.name,e=a.body,f=b.form;if(c&&"post_title"==c&&e&&e.className&&0<=e.className.indexOf("wp-admin")||c&&("symbols"==c||"symbol"==c)||"text"==b.type&&d&&(0<d.indexOf("_note")||0<d.indexOf("-note")))return!0;e=RegExp(lpgs("ff_combineddummy_regexp"),"i");return e.exec(d)||e.exec(c)?(decision_log(a,"DE22",{param1:d,param2:c}),!0):f&&!popupfill_shoulddoform(a,f)?!0:!1}function LP_read_website_hint(){}
function should_ignore_body_relative(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","ignore-relative-style");if(!0===b||!1===b)return b;b=0;b=null;LP_get_cached_body_rect(a);var b=LP_get_body_reference(a),d=LP_get_cached_body_style(a);if(d&&"relative"!=d.position)return formcacheset(a,"fakedoc","ignore-relative-style",!0),!0;d=[];b&&(d=b.children);if(d&&0<d.length){Checkpoint.assert(100>d.length,"too many body.children");for(b=0;b<d.length&&100>b;b++)if(!lp_in_array(d[b].tagName.toUpperCase(),
["SCRIPT"])&&lp_in_array(d[b].tagName.toUpperCase(),["DIV","SECTION","FORM"])){if((b=LP_get_live_style(d[b]))&&"relative"==b.position)return formcacheset(a,"fakedoc","ignore-relative-style",!1),!1;break}}formcacheset(a,"fakedoc","ignore-relative-style",!0);return!0}
function LP_iconFieldWidthOK(a,b,d){if(!a||null===b)return!1;var c=a.ownerDocument;if(!c)return verbose_log("iconFieldWidthOK: no doc???"),!1;if("undefined"==typeof d||null===d)if(isInputFieldPassword(c,a))d=!0;else{var e=a.form;e&&chk_form_has_password(c,e)&&(d=!0)}d?0<b&&40>b?a=!1:(a?(b=a.getAttribute("size"),d=a.getAttribute("maxlength"),null==b&&(b=a.size),null==d&&(d=a.maxLength),a=""==a.style.width&&b&&2>b&&0<=b||d&&3>d&&0<=d?!1:!0):a=!1,a=!a?!1:!0):a=0<b&&100>b?!1:!0;return a}
function create_icons_on_ASP(a,b){if(do_experimental_popupfill){a||(a=LP_derive_doc());if(!a)return!1;decision_log(a,"DD21",{param1:a.location.href});var d=[];if(g_do_icon_number_hint)if(g_isfirefox){var c=LP.getMatchingSites(a.location.href,SKIP_GENPWS);d.sites=c&&c.length?c.length:0}else d=g_icon_numbers;var c=a.getElementsByTagName("FORM"),e,f,j=SHOULD_DO_ALWAYS,l=LP_getFormsThreshold(a),n=0;for(f=0;f<c.length&&f<l;f++){var g=c[f].elements;chk_form_has_password(a,c[f]);chk_form_is_nonlogin_form(a,
c[f]);chk_form_ask_generate(a,c[f]);var q=form_get_username(a,c[f]),s=form_get_password(a,c[f]),h=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(h=MAX_INPUTS_HARD);for(e=0;e<g.length&&e<h;e++){var m=!1,p=g[e],r="sites";if("INPUT"==p.tagName){var k=!1;if(popupfill_shoulddofield(a,p,j)){var t=LP_fieldGetWidth(p),u=!0;if(b){if(looksLikeUsername(p)||isInputFieldPassword(a,p))r="sites",m=!0}else if(q==p)r="sites",m=!0;else if(isInputFieldPassword(a,p))p==lpCheckCurrentPWField(c[f],!0)?(r="sites",k=m=!0):
s==p?(r="sites",k=m=!0):isContigPW(a,p.form,p)?(r="generate",m=!0):(r="sites",k=m=!0);else if(isFirstFieldNonLoginSubForm(a,p))r="formfills",m=!0,u=!1;else if(isUsernameFieldLoginSubForm(a,p)||isPasswordFieldLoginSubForm(a,p))r="sites",k=m=!0;if(m&&LP_iconFieldWidthOK(p,t,u)&&(n++,setup_input_icon(a,p,r,d,k),g_clickable_input&&(!("password"==p.type&&formHasUsernameField(p))||g_clickable_input_on_password)&&!LP_didFieldClickEvent(a,p)&&r&&"sites"==r))LP_setFieldClickEvent(a,p),LP_addEventHandler(p,
"click",function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,p.form),popuptoggle(a,null,LP_getname_or_idx(a,p,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(e){}return!1},!1)}}}}decision_log(a,
"DE1",{param1:n})}}
function check_for_ASP(a,b){if(b&&!isASPpage()&&g_aspx_hack){if((0===b.name.indexOf("ctl00$")||null!=b.form&&("ctl00"==b.form.name||"landingform"==b.form.name||"landingForm"==b.form.name||"aspnetForm"==b.form.name||"aspnetForm"==b.form.id)||0===b.name.indexOf("ctl00_"))&&!isASPpage())setASPpage(!0),decision_log("DE20");try{a.location&&(a.location.href&&0<a.location.href.indexOf(".aspx"))&&(b.form&&(b.form.elements&&b.form.elements.length&&6<b.form.elements.length)&&!isASPpage())&&(setASPpage(!0),
decision_log("DE19"))}catch(d){write_error_to_history(a,"check_for_ASP",d)}}}
function create_icons_generic(a,b){if(do_experimental_popupfill){if(!a&&(a=LP_derive_doc(),!a))return null;decision_log(a,"DE16",{param1:a.location.href});var d=[];if(g_do_icon_number_hint)if(g_isfirefox){var c=LP.getMatchingSites(a.location.href,SKIP_GENPWS);d.sites=c&&c.length?c.length:0}else d=g_icon_numbers;var c=a.getElementsByTagName("INPUT"),e,f=c.length;e=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(e=MAX_INPUTS_HARD);Checkpoint.assert(f<=e,"page has too many inputs");f>e&&(f=e);var j=SHOULD_DO_ALWAYS,
l=checkDocumentForLoginOrphans(a);LP_firstVisibleOrphan(a);var n=0;for(e=0;e<f;e++){var g=c[e].form,q=null,s=null;g?(q=form_get_username(a,g),s=form_get_password(a,g)):(q=doc_get_orphan_username(a),s=doc_get_orphan_password(a));var h=c[e],m=!1,p="sites",r=!1;if(popupfill_shoulddofield(a,h,j)){var k=LP_fieldGetWidth(h),t=!0;if(b){if(looksLikeUsername(h)||isInputFieldPassword(a,h))p="sites",m=!0}else if(q==h)p="sites",m=!0;else if(isInputFieldPassword(a,h))g&&h==lpCheckCurrentPWField(g,!0)?(p="sites",
r=m=!0):lpIsFieldCurrentPWField(h)?(p="sites",r=m=!0):s==h?(p="sites",r=m=!0):isContigPW(a,h.form,h)?(p="generate",m=!0):(p="sites",r=m=!0);else if(isFirstFieldNonLoginSubForm(a,h))p="formfills",m=!0,t=!1;else if(isUsernameFieldLoginSubForm(a,h)||isPasswordFieldLoginSubForm(a,h))p="sites",r=m=!0;else if(null==h.form&&l&&(looksLikeUsername(h)||isInputFieldPassword(a,h)))p="sites",m=!0;if(m&&LP_iconFieldWidthOK(h,k,t)&&(n++,setup_input_icon(a,h,p,d,r),g_clickable_input&&(!("password"==h.type&&formHasUsernameField(h))||
g_clickable_input_on_password)&&!LP_didFieldClickEvent(a,h)&&p&&"sites"==p))LP_setFieldClickEvent(a,h),LP_addEventHandler(h,"click",function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,h.form),popuptoggle(a,null,LP_getname_or_idx(a,h,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));
else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(e){}return!1},!1)}}decision_log(a,"DE2",{param1:n});return!0}}
function LP_getAngularAttributes(a,b){a||(a=LP_derive_doc());if(!b||!a)return null;for(var d={},c="ng-model ng-controller ng-repeat ng-include ng-switch ng-view".split(" "),e=0;e<c.length;e++){var f=b.getAttribute(c[e]);null!==f&&(d[c[e]]=f)}c="ng-valid ng-invalid ng-pristine ng-dirty ng-touched ng-untouched ng-pending ng-empty ng-not-empty".split(" ");for(e=0;e<c.length;e++)f=sprintf("[\\w]*%s[\\w]*",c[e]),b.className.match(f)&&(d[c[e]]=!0);return d}
function LP_hasAngular(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,d=a.documentElement;if((a=a.body)&&a.getAttribute("ng-app")||d&&d.getAttribute("ng-app"))b=!0;return b}function LP_hasKnockout(a){a||LP_derive_doc();return!1};
