document.title=gs("My LastPass Vault");document.getElementById("lp_docwrite_homelocal21")&&(document.getElementById("lp_docwrite_homelocal21").innerHTML=gs("Log Out"));document.getElementById("lp_docwrite_homelocal22")&&(document.getElementById("lp_docwrite_homelocal22").innerHTML=gs("Open Favorites"));document.getElementById("lp_docwrite_homelocal23")&&(document.getElementById("lp_docwrite_homelocal23").innerHTML=gs("Bookmarklets"));
document.getElementById("lp_docwrite_homelocal24")&&(document.getElementById("lp_docwrite_homelocal24").innerHTML=gs("History"));document.getElementById("lp_docwrite_homelocal25")&&(document.getElementById("lp_docwrite_homelocal25").innerHTML=gs("Import"));document.getElementById("lp_docwrite_homelocal26")&&(document.getElementById("lp_docwrite_homelocal26").innerHTML=gs("Export"));document.getElementById("lp_docwrite_homelocal27")&&(document.getElementById("lp_docwrite_homelocal27").innerHTML=gs("One Time Passwords"));
document.getElementById("lp_docwrite_homelocal28")&&(document.getElementById("lp_docwrite_homelocal28").innerHTML=gs("Show Deleted Sites"));document.getElementById("lp_docwrite_homelocal29")&&(document.getElementById("lp_docwrite_homelocal29").innerHTML=gs("Actions"));document.getElementById("lp_docwrite_homelocal30")&&(document.getElementById("lp_docwrite_homelocal30").innerHTML=gs("Generate Secure Password"));
document.getElementById("lp_docwrite_homelocal210")&&(document.getElementById("lp_docwrite_homelocal210").innerHTML=gs("Admin Console"));document.getElementById("lp_docwrite_homelocal211")&&(document.getElementById("lp_docwrite_homelocal211").innerHTML=gs("Manage Shared Folders"));document.getElementById("lp_docwrite_homelocal212")&&(document.getElementById("lp_docwrite_homelocal212").innerHTML=gs("Account Settings"));
document.getElementById("lp_docwrite_homelocal212a")&&(document.getElementById("lp_docwrite_homelocal212a").innerHTML=gs("Tools"));document.getElementById("lp_docwrite_homelocal212b")&&(document.getElementById("lp_docwrite_homelocal212b").innerHTML=gs("Select Identity"));document.getElementById("lp_docwrite_homelocal212c")&&(document.getElementById("lp_docwrite_homelocal212c").innerHTML=gs("Open Favorites in Tabs"));
document.getElementById("lp_docwrite_homelocal212d")&&(document.getElementById("lp_docwrite_homelocal212d").innerHTML=gs("Generate Secure Password"));document.getElementById("lp_docwrite_homelocal212e")&&(document.getElementById("lp_docwrite_homelocal212e").innerHTML=gs("Advanced Tools"));document.getElementById("lp_docwrite_homelocal212f")&&(document.getElementById("lp_docwrite_homelocal212f").innerHTML=gs("Bookmarklets"));
document.getElementById("lp_docwrite_homelocal212g")&&(document.getElementById("lp_docwrite_homelocal212g").innerHTML=gs("One Time Passwords"));document.getElementById("lp_docwrite_homelocal212h")&&(document.getElementById("lp_docwrite_homelocal212h").innerHTML=gs("Show Deleted Items"));document.getElementById("lp_docwrite_homelocal212i")&&(document.getElementById("lp_docwrite_homelocal212i").innerHTML=gs("View History"));
document.getElementById("lp_docwrite_homelocal212j")&&(document.getElementById("lp_docwrite_homelocal212j").innerHTML=gs("Import"));document.getElementById("lp_docwrite_homelocal212k")&&(document.getElementById("lp_docwrite_homelocal212k").innerHTML=gs("Export"));document.getElementById("lp_docwrite_homelocal213")&&(document.getElementById("lp_docwrite_homelocal213").innerHTML=gs("Add Site"));
document.getElementById("lp_docwrite_homelocal214")&&(document.getElementById("lp_docwrite_homelocal214").innerHTML=gs("Add Secure Note"));document.getElementById("lp_docwrite_homelocal215")&&(document.getElementById("lp_docwrite_homelocal215").innerHTML=gs("Create Group"));document.getElementById("lp_docwrite_homelocal216")&&(document.getElementById("lp_docwrite_homelocal216").innerHTML=gs("User Manual"));
document.getElementById("lp_docwrite_homelocal216a")&&(document.getElementById("lp_docwrite_homelocal216a").innerHTML=gs("Tutorials"));document.getElementById("lp_docwrite_homelocal216c")&&(document.getElementById("lp_docwrite_homelocal216c").innerHTML=gs("Log Out"));document.getElementById("lp_docwrite_homelocal217")&&(document.getElementById("lp_docwrite_homelocal217").innerHTML=gs("Security Challenge"));
document.getElementById("lp_docwrite_homelocal217a")&&(document.getElementById("lp_docwrite_homelocal217a").innerHTML=gs("Expand All Folders"));document.getElementById("lp_docwrite_homelocal217b")&&(document.getElementById("lp_docwrite_homelocal217b").innerHTML=gs("Collapse All Folders"));document.getElementById("lp_docwrite_homelocal218")&&(document.getElementById("lp_docwrite_homelocal218").innerHTML=gs("Vault"));
document.getElementById("lp_docwrite_homelocal219")&&(document.getElementById("lp_docwrite_homelocal219").innerHTML=gs("Form Fill Profiles"));document.getElementById("lp_docwrite_homelocal220")&&(document.getElementById("lp_docwrite_homelocal220").innerHTML=gs("Identities"));document.getElementById("lp_docwrite_homelocal221")&&(document.getElementById("lp_docwrite_homelocal221").innerHTML=gs("Shares"));
document.getElementById("lp_docwrite_homelocal222")&&(document.getElementById("lp_docwrite_homelocal222").innerHTML=gs("Credit Monitoring"));document.getElementById("lp_docwrite_homelocal223")&&(document.getElementById("lp_docwrite_homelocal223").innerHTML=gs("Enterprise"));document.getElementById("lp_docwrite_homelocal224")&&(document.getElementById("lp_docwrite_homelocal224").innerHTML=gs("Tutorials"));
document.getElementById("lp_docwrite_homelocal225")&&(document.getElementById("lp_docwrite_homelocal225").innerHTML=upperFirstChar(gs("Name")));document.getElementById("lp_docwrite_homelocal226")&&(document.getElementById("lp_docwrite_homelocal226").innerHTML=upperFirstChar(gs("Actions")));document.getElementById("lp_docwrite_homelocal227")&&(document.getElementById("lp_docwrite_homelocal227").innerHTML=upperFirstChar(gs("Username")));
document.getElementById("lp_docwrite_homelocal228")&&(document.getElementById("lp_docwrite_homelocal228").innerHTML=upperFirstChar(gs("Last used")));document.getElementById("lp_docwrite_homelocal229")&&(document.getElementById("lp_docwrite_homelocal229").innerHTML=gs("Help spread the word"));document.getElementById("lp_docwrite_homelocal229a")&&(document.getElementById("lp_docwrite_homelocal229a").innerHTML=gs("Invite Friends To Try LastPass"));
document.getElementById("lp_docwrite_homelocal230")&&(document.getElementById("lp_docwrite_homelocal230").innerHTML=gs("Do you like LastPass?"));document.getElementById("lp_docwrite_homelocal231a")&&(document.getElementById("lp_docwrite_homelocal231a").innerHTML=gs("Give the Gift of LastPass"));document.getElementById("lp_docwrite_homelocal231")&&(document.getElementById("lp_docwrite_homelocal231").innerHTML=gs("Tell a friend!"));
document.getElementById("lp_docwrite_homelocal232")&&(document.getElementById("lp_docwrite_homelocal232").innerHTML=gs("GET FREE PREMIUM"));document.getElementById("lp_docwrite_homelocal233")&&(document.getElementById("lp_docwrite_homelocal233").innerHTML=gs("Link Personal Account"));document.getElementById("lp_docwrite_homelocal234")&&(document.getElementById("lp_docwrite_homelocal234").innerHTML=gs("Remove Linked Personal Account"));
document.getElementById("lp_docwrite_homelocal235")&&(document.getElementById("lp_docwrite_homelocal235").innerHTML=gs("LastPass Legacy"));
if(g_issafari||g_isopera)document.getElementById("searchx")&&(document.getElementById("searchx").src=getchromeurl("images/cancel.png"),document.getElementById("searchx").style.marginTop="-2px"),document.getElementById("enterpriseicon")&&(document.getElementById("enterpriseicon").src=getchromeurl("images/enterprise.png")),document.getElementById("managedicon")&&(document.getElementById("managedicon").src=getchromeurl("images/manage_shared.png")),document.getElementById("linkicon")&&(document.getElementById("linkicon").src=
getchromeurl("images/link_account.png")),document.getElementById("linkicon2")&&(document.getElementById("linkicon2").src=getchromeurl("images/link_account.png")),document.getElementById("settingsicon")&&(document.getElementById("settingsicon").src=getchromeurl("images/settings.png")),document.getElementById("addsiteicon")&&(document.getElementById("addsiteicon").src=getchromeurl("images/add_site.png")),document.getElementById("securenoteicon")&&(document.getElementById("securenoteicon").src=getchromeurl("images/secure_note2.png")),
document.getElementById("creategroupicon")&&(document.getElementById("creategroupicon").src=getchromeurl("images/create_group.png")),document.getElementById("lpexpandimg")&&(document.getElementById("lpexpandimg").src=getchromeurl("images/folder_open.png")),document.getElementById("lpcollapseimg")&&(document.getElementById("lpcollapseimg").src=getchromeurl("images/folder_close.png")),document.getElementById("searchicon")&&(document.getElementById("searchicon").src=getchromeurl("images/search_lite.png"));
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){onLoad()});window.addEventListener("unload",function(){onUnLoad()});window.addEventListener("resize",function(){onResize()});document.getElementById("searchform").onsubmit=function(){SearchTree();return!1};document.getElementById("lpwebsiteeventform").onsubmit=function(){website_event();return!1};document.getElementById("lplogoff").onclick=function(){logoff();return!1};document.getElementById("lpopenfavorites").onclick=
function(){closepopup();getBG().lpevent("v_of");getBG().openfavorites();return!1};document.getElementById("lpbookmarklets").onclick=function(){closepopup();getBG().lpevent("v_bk");callServerFunction("bookmarklets");return!1};document.getElementById("lphistory").onclick=function(){closepopup();getBG().lpevent("v_his");callServerFunction("history");return!1};document.getElementById("lpimport").onclick=function(){closepopup();getBG().lpevent("v_i");getBG().openimport();return!1};document.getElementById("lpexport").onclick=
function(){closepopup();getBG().lpevent("v_e");getBG().openexport();return!1};document.getElementById("lpadvtools").onclick=function(){return!1};document.getElementById("lpotp").onclick=function(){closepopup();getBG().lpevent("v_otp");openinparent("otp.php");return!1};document.getElementById("lpdeleted").onclick=function(){closepopup();getBG().lpevent("v_sd");getBG().unlock_plug2web();openinparent("",{ac:"1",showdeleted:"1"});return!1};document.getElementById("lpenterprise").onclick=function(){getBG().lpevent("v_ec");
openinparent("enterprise_home.php");return!1};document.getElementById("lpsharedfolders").onclick=function(){getBG().lpevent("v_sf");callServerFunction("sharedfolders");return!1};document.getElementById("lpsettings").onclick=function(){getBG().lpevent("v_set");callServerFunction("settings");return!1};document.getElementById("lpadd").onclick=function(){openaddbytab();return!1};document.getElementById("lpaddnote").onclick=function(){getBG().openaddsecurenote();return!1};document.getElementById("lpcreategroup").onclick=
function(){creategroup();return!1};document.getElementById("lphelp").onclick=function(){getBG().lpevent("v_hlp");openinparent("help.php");return!1};document.getElementById("lpseccheck").onclick=function(){getBG().lpevent("v_sc");getBG().openseccheck();return!1};document.getElementById("lpexpandall").onclick=function(){expandall();return!1};document.getElementById("lpcollapseall").onclick=function(){collapseall();return!1};document.getElementById("lpfriendemail").onclick=function(){openinparent("friendemail.php");
return!1};document.getElementById("lpgift").onclick=function(){openinparent("gift.php?f=0002");return!1};document.getElementById("q").addEventListener("keyup",function(a){34==a.keyCode||33==a.keyCode||40==a.keyCode||38==a.keyCode?MoveFocus(a):gSearchWhileType&&13!=a.keyCode&&(document.getElementById("q"),document.getElementById("searchx").src=gLocalBaseUrl+"images/search.png",SearchTree())});document.getElementById("searchxlink").onclick=function(){""==document.getElementById("q").value?document.getElementById("searchx").src=
gLocalBaseUrl+"images/search.png":(document.getElementById("searchx").src=gLocalBaseUrl+"images/search.png",getBG().lpevent("v_x"),clearTree());document.getElementById("q").focus();return!1};document.getElementById("logo").addEventListener("click",function(){document.location.href=getpartnerurl(g_urlprefix)});document.getElementById("identity").addEventListener("change",function(){changeidentity(this.value,!1);return!1});document.getElementById("sites").addEventListener("click",function(){ontabchange(this)});
document.getElementById("ff").addEventListener("click",function(){ontabchange(this)});document.getElementById("ident").addEventListener("click",function(){ontabchange(this)});document.getElementById("shares").addEventListener("click",function(){ontabchange(this)});document.getElementById("credmon").addEventListener("click",function(){ontabchange(this)});document.getElementById("enterprise").addEventListener("click",function(){ontabchange(this)});document.getElementById("chooser").addEventListener("click",
function(){toggleUserCol()});document.getElementById("lplinkpersonal").onclick=function(){getBG().lpevent("v_lp");callServerFunction("linkpersonal");return!1};document.getElementById("lpremovepersonal").onclick=function(){getBG().lpevent("v_rp");callServerFunction("removepersonal",get_personal_linked(),getBG().g_token);return!1};document.getElementById("toolsturner").addEventListener("click",function(){showTools();return!1});document.getElementById("lptutorials").addEventListener("click",function(){openinparent("support_screencasts.php");
return!1});document.getElementById("lppopuplink").onclick=function(){"block"===document.getElementById("lppopup").style.display?closepopup():(getBG().lpevent("v_pop"),showpopup());return!1};document.getElementById("legacy_a").onclick=function(){getBG().lpevent("v_lg");getBG().openlastpasslegacy();return!1};window.addEventListener("resize",hide_promo);hide_promo();setTimeout(hide_promo,2E3)});
function hide_promo(){if("1"!=getBG().g_enterpriseuser){var a="",a=-1!=$("#lpfriendemail").css("display").indexOf("block")?"#lpfriendemail":-1!=$("#lpgift").css("display").indexOf("block")?"#lpgift":pick_promo();$(a).css("display","block");$("#actions").height()>=$(a).position().top&&$(a).css("display","none")}}function pick_promo(){var a=new Date,b=Math.floor(100*Math.random());return 10==a.getMonth()&&25<=a.getDate()||11==a.getMonth()&&25>=a.getDate()&&25<b?"#lpgift":"#lpfriendemail"}
function showTools(){var a=document.getElementById("turnericon").classList.toggle("turn90");document.getElementById("toolspane").style.display=a?"block":"none";hide_promo()}g_isfirefoxsdk&&document.getElementById("searchicon")&&(document.getElementById("searchicon").style.position="absolute",document.getElementById("searchicon").style.top="2px");
