function LP_field_set_backgroundPosition(b,a){b||(b=LP_derive_doc());if(!b||!a)return!1;var d=!1;if(!0===LP_get_text_dir(a)){var c="center right";if(null!=typeof a.style.backgroundPosition)lp_in_array(a.style.backgroundPosition,["center right","right center","100% 50%","right"])||(d=!0);else if(g_isie&&null!=typeof a.currentStyle&&null!=typeof a.currentStyle.backgroundPositionX&&null!=typeof a.currentStyle.backgroundPositionY){var f=a.currentStyle.backgroundPositionX,e=a.currentStyle.backgroundPositionY;
if(!lp_in_array(f,"right","100%")||!lp_in_array(e,"center","50%"))d=!0}}else if(c="center left",null!=typeof a.style.backgroundPosition)lp_in_array(a.style.backgroundPosition,["center left","left center","0% 50%","left"])||(d=!0);else if(g_isie&&(null!=typeof a.currentStyle&&null!=typeof a.currentStyle.backgroundPositionX&&null!=typeof a.currentStyle.backgroundPositionY)&&(f=a.currentStyle.backgroundPositionX,e=a.currentStyle.backgroundPositionY,!lp_in_array(f,"left","0%")||!lp_in_array(e,"center",
"50%")))d=!0;d&&(a.style.backgroundPosition=c);return!0}function LP_get_text_dir(b){var a=!0;if(b){var d=LP_get_live_style(b);d&&"rtl"==d.direction?a=!1:"rtl"==b.getAttribute("dir")&&(a=!1)}return a}
function LP_input_has_bg_style_override(b){if(!b||!g_stylesheet_grubbing)return!1;var a=!1;try{var d=formcacheget(b,"fakedoc","input-bg-style");if(null!=d)return d;var c=d=0,f=/(background|background-color):[^:].*!important/,e=b.styleSheets;if(e&&f)for(d=0;d<e.length&&32>d;d++){var g=null;"undefined"!=typeof e[d].rules?g=e[d].rules:"undefined"!=typeof e[d].cssRules&&(g=e[d].cssRules);if(g){for(c=0;c<g.length;c++)if(g[c]&&g[c].selectorText&&g[c].cssText&&-1!=g[c].selectorText.indexOf("input:focus")){var h=
g[c].cssText;if(h&&f.exec(h)){verbose_log("focus hack:"+h);a=!0;break}}if(a)break}}}catch(j){}formcacheset(b,"fakedoc","input-bg-style",a);return a}
function ForceFillOrphanFieldClicked(b,a,d){if(!b&&(b=elt.ownerDocument,!b))return!1;var c=!0;if(c=ForceFillFieldClicked(b,a,!1,d))for(var f=b.getElementsByTagName("INPUT"),e=0,e=0;e<f.length&&e<MAX_INPUTS_HARD;e++)if(f[e]==a&&f[e+1]&&e+1<f.length&&e+1<MAX_INPUTS_HARD){isInputFieldPassword(b,f[e+1])&&!lpIsFieldCurrentPWField(f[e+1])&&(c=ForceFillFieldClicked(b,f[e+1],!1,d));break}return c}
function revert_clickable_icon(b,a){verbose_log("entered revert_clickable_icon");if(null!=b){var d=LP_getElementByIdOrName(b,a),c=getIconState(b,a),f=!1,e="sites";c&&"undefined"!=typeof c.dofloater&&(f=c.dofloater);c&&"undefined"!=typeof c.fillhint&&(e=c.fillhint);verbose_log("entered BG image revert");d?f?reset_floating_icon(b,d,e):set_input_icon_image(b,d,e):verbose_log("could not find field named "+field_id)}}function conditional_create_popup(){return!1}
function closeclickableicons(b){if(do_experimental_popupfill&&(b||(b=document),null!=b)){verbose_log("closeclickableicons called on "+b.location.href);var a=getAllIconStates(),d,c;for(d=0;d<a.length;d++){var f=a[d];(c=f.IHTMLElement)||(c=LP_getElementByIdOrName(b,f.idorname));if(!f.dofloat&&f.inframe&&!c)if(g_isfirefox)try{var e,g,h=b.getElementsByTagName("IFRAME");for(e=0;e<h.length;e++)g=h[e].contentDocument,(c=LP_getElementByIdOrName(g,f.idorname))&&"INPUT"==c.tagName&&removeLPBackground(c)}catch(j){verbose_log("Error frame traverse "+
j.message),g=null}else!g_isie&&g_create_iframe_in_top&&pass;else!f.dofloater&&(c&&inputHasLPBackground(c))&&removeLPBackground(c);resetAllIconStates()}a=LP_get_icon_divs(b);for(e in a)a.hasOwnProperty(e)&&null!=b.getElementById(a[e])&&(g_do_icon_number_hint&&LP_delete_floating_icon_hint(b,a[e]),LP_delete_floating_icon(b,a[e]));LP_reset_icon_divs(b)}}
function setup_input_icon(b,a,d,c,f){var e=!1;if(null==a)return verbose_log("setup_input_icon: ERROR passed null field"),e;if(a.form&&"sites"==d&&is_shopping_form(b,a.form)&&g_aspx_hack&&(isASPpage()&&2<b.getElementsByTagName("form").length||!isASPpage()))return e;g_isfirefox&&(LP&&"undefined"!=typeof g_icon_number_in_toolbar&&g_icon_number_in_toolbar)&&LP.lp_handle_buttons_all("refresh");var g=null,g="undefined"!=typeof LP&&"function"==typeof LP.lpGetCurrentWindow?"undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?
LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument:g_isfirefox?top.document:document;if(!do_experimental_popupfill)return e;b||(b=g);var h=LP_pickFieldName(b,a);if(null==a||(!g||!b)||LP_explicit_ignored(b,a))return e;if((e=getIconState(b,h))&&e.IHTMLElement==a&&(inputHasLPBackground(a)||LP_floating_icon_exists(b,h)))return!1;e=null;if("generate"==d||!f&&shouldOfferGenerate(b,a))d="generate";var j=gettldcached(b.location.href),e=shouldCreateFloatingIcon(b,a,j),k=LP_get_text_dir(a);
!1===k&&pass;if(LP_fieldIsReadOnly(a)||LP_fieldIsDisabled(a))return!1;g=b!=g;g_create_iframe_in_top&&(!g_isie&&!g_isfirefox&&LP_inIframe(window))&&(g=!0);f={fillhint:d,fillhintnumber:c[d],inframe:g,idorname:h,doctld:j,dofloater:e?1:0,no_check_generate:f?1:0,IHTMLElement:a,text_direction:k};if(e)if(g_isfirefox&&verbose_log("setup_input_icon step3b"),lpIsVisible(a)&&(null==a.form||a.form&&lpIsVisible(a.form)))saveIconState(h,f,a),e=LP_create_floating_icon(b,a,d,c);else return!1;else saveIconState(h,
f,a),e=set_input_icon_image(b,a,d,!1);set_bg_highlight_effect_handlers(b,a,d);LP_didDocumentEscapeEvent(b)||(LP_setDocumentEscapeEvent(b),LP_addEventHandler(b,"keydown",function(a){LP_keypress_handler(a)},!1));LP_didFieldKeyEvent(b,a)?verbose_log("skip KEYDOWN HANDLER ON "+LP_pickFieldName(b,a)):(verbose_log("SETTING KEYDOWN HANDLER ON "+LP_pickFieldName(b,a)),LP_setFieldKeyEvent(b,a),LP_addEventHandler(a,"keydown",function(c){LP_field_keypress_handler(c,a,d,b)},!1),g_isfirefox&&LP_addEventHandler(a,
"keyup",function(c){handle_form_text_change(b,a,a.form,c)},!1));return e}function refresh_input_icon_bg(b,a,d){if(!b&&(b=LP_derive_doc(),!b))return null;a&&set_input_icon_image(b,a,d,!1)}
function refresh_input_all_icon_bg(b){null==b&&(b=document);if(null!=b){try{if(0<b.location.href.indexOf(".xul"))return;verbose_log("refreshing input icons on "+b.location.href)}catch(a){return}var d=getAllIconStates(),c;for(c=0;c<d.length;c++){var f=d[c].idorname,e=d[c].fillhint,g=d[c].dofloater,h=d[c].IHTMLElement;element_is_detached(b,h,0)&&(h=null);h||(h=LP_getElementByIdOrName(b,f));h&&!g&&refresh_input_icon_bg(b,h,e)}}}var origstyle={};
function set_input_icon_image(b,a,d,c){var f,e=[];e[0]=g_sites_light_ico;e[1]=g_pw_light_ico;e[3]=g_close_light_ico;e[-1]="";e[2]=g_ff_light_ico;e[16]=g_sites_ico;e[17]=g_pw_ico;e[19]=g_close_ico;e[-17]="";e[18]=g_ff_ico;if(null==a||a.tagName&&"undefined"!=typeof a.tagName.toUpperCase&&"INPUT"!=a.tagName.toUpperCase())return!1;"undefined"==typeof d||null==d?f=0:"formfills"==d?f=2:"sites"==d?f=0:"generate"==d?f=1:"cancel"==d&&(f=3);c&&(f|=16);var g=LP_fieldGetWidth(a),h=!1;if("sites"==d||g_is_specialsite)h=
!0;if(!LP_iconFieldWidthOK(a,g,h))return!0;d=a.style.border;g=a.style.backgroundImage;if(""==g)if(origstyle[a]=j,"undefined"!=typeof g_isie&&g_isie&&a.currentStyle)g=a.currentStyle.backgroundImage,d=a.currentStyle.border;else try{var j=a.ownerDocument.defaultView.getComputedStyle(a,""),g=j.backgroundImage;d=j.border}catch(k){"undefined"!=typeof a.currentStyle&&(g=a.currentStyle.backgroundImage,d=a.currentStyle.border)}"none"==g&&(g="");0<=f&&("undefined"==typeof e[f]&&verbose_log("no icon defined for iconval="+
f),c=LP_getloggedin()?0==f||16==f?getnumbericon(b,a,c):e[f]:e[f],g!="url("+c+")"&&(a.style.backgroundImage="url("+c+")",c=a.ownerDocument.location.href,0<=c.indexOf("live.com")?a.style.paddingRight="18px":0<=c.indexOf("twitter.com")&&(a.style.paddingRight="16px"),g_issafari&&""!==d&&0<d.indexOf("inset")&&d.replace("inset",""),"no-repeat"!=a.style.backgroundRepeat&&(a.style.backgroundRepeat="no-repeat"),"scroll"!=a.style.backgroundAttachment&&(a.style.backgroundAttachment="scroll"),LP_field_set_backgroundPosition(b,
a)));return!0}function set_bg_highlight_effect_handlers(b,a,d){a&&(LP_didFieldMouseEvent(b,a)||(LP_setFieldMouseEvent(b,a),LP_addEventHandler(a,"mouseover",function(c){bg_highlight_effect_mouseover(c,b,a,d)}),LP_addEventHandler(a,"mouseout",function(c){bg_highlight_effect_mouseout(c,b,a,d)}),LP_addEventHandler(a,"mousemove",function(c){bg_highlight_effect_mousemove(c,b,a,d)})),"sites"==d&&LP_getloggedin()&&(!g_isfirefox&&!g_isie)&&a.setAttribute("autocomplete","off"))}
function bg_highlight_effect_mousemove(b,a,d){null==b&&(b=window.event);b=LP_getMousePos(b);if(!(0>=b.x&&0>=b.y))if(a=LP_getAbsolutePos(a,d),0>=a.width&&0>=a.height)verbose_log("skipping field "+obj.idorname+" : no valid position");else{var c=a.left+a.width-20;c<a.left&&(c=a.left);d.style.cursor=c<b.x&&a.left+a.width>b.x&&a.top<b.y&&a.top+a.height>b.y?"pointer":"auto"}}
function bg_highlight_effect_mouseover(b,a,d,c){null==b&&(b=window.event);if(!(is_your_popup_showing(a)&&a.g_popupfill_parent==d)&&LP_getEventTarget(b)==d){b=c;c=!1;var f=getIconState(a,LP_pickFieldName(a,d));!b&&(f&&f.hint)&&(b=f.hint);f&&f.dofloater&&(c=f.dofloater);b&&!c&&set_input_icon_image(a,d,b,!0)}}
function bg_highlight_effect_mouseout(b,a,d,c){if(!(is_your_popup_showing(a)&&a.g_popupfill_parent==d)){b=c;c=!1;var f=getIconState(a,LP_pickFieldName(a,d));!b&&(f&&f.hint)&&(b=f.hint);f&&f.dofloater&&(c=f.dofloater);b&&!c&&set_input_icon_image(a,d,b,!1)}}
function popuptoggle(b,a,d,c,f,e,g,h,j,k){if(k)j=k;else if(a){if(0<a.location.href.indexOf(".xul"))return!0;j=LP_getElementByIdOrName(a,d)}else{if(0<b.location.href.indexOf(".xul"))return!0;j=LP_getElementByIdOrName(b,d)}"undefined"!=typeof reset_forcefill_without_fillbest&&reset_forcefill_without_fillbest();k="sites";c?k="generate":e?k="save":g&&(k="formfills");if(is_your_popup_showing(b))closepopupfills(b),g_isfirefox?a?(a.g_popupfill_parent_last=a.g_popupfill_parent,a.g_popupfill_parent=null):
(b.g_popupfill_parent_last=b.g_popupfill_parent,b.g_popupfill_parent=null):(g_popupfill_parent_last=g_popupfill_parent,g_popupfill_parent=null);else{g=LP_getloggedin();if(!g){if("undefined"!=typeof LP&&"undefined"!=typeof LP.lpOpenLogin){LP.lpOpenLogin();return}if(!g_isie){sendBG({cmd:"dologinaction"});return}}g_isfirefox?a?a.g_popupfill_parent=j:b.g_popupfill_parent=j:g_popupfill_parent=j;e=e?!0:!1;g_isie?"undefined"!=typeof init_LPfn&&init_LPfn()&&LPfn.ie_set_lpifmsg(b,j,c,e,k,h):g_isfirefox||(h=
LP_pickFormName(j.ownerDocument,j.form),c=c?1:0,sendBG({cmd:"setpopupfilllastactive",active:h,activefieldid:LP_pickFieldName(document,j),ask_generate:c,opentosave:e,activefieldtype:j.type,start_type:k}));!g_isfirefox&&!g_isie&&(g=document.location.href,"undefined"!=typeof punycode&&(g=punycode.URLToASCII(document.location.href)),sendBG({cmd:"popupregister",docnum:g_docnum,url:g}));h=("function"==typeof ff_calculate_iframe_pos?ff_calculate_iframe_pos:calculate_iframe_pos)(b,j,"300px",should_ignore_body_relative(b));
c=h.posx;h=h.posy;if(g_isfirefox)ff_popupfill_create_iframe(b,c,h,d,null,null,j,k);else{e=chk_form_is_nonlogin_form(document,j.form);k=checkDocumentForLoginOrphans(document)||checkDocumentForLoginOrphansFirstStage(document);g=checkDocumentForLoginFirstStageForm(document);g=k||g||chk_form_has_password(document,j.form);k=g_popupfill_rows;e&&!g&&(k=g_popupfill_rows_FF);e=g_popupfill_widest+40;120>e&&(e=120);e<g_popupfill_parent.offsetWidth&&(e=g_popupfill_parent.offsetWidth,e+=2*Math.abs(POPUP_FIELD_OFFSET));
if(1==k&&!create_onerow_iframe){g=null;g_fillaid&&(g=g_fillaid);isEmptyObject(g_autofillsites)||(g=g_autofillsites[0].aid);if(null!=g){sendBG({cmd:"autofillaid",aid:g});verbose_log("filling only, not creating 1 row iframe");return}verbose_log("tried to fill form with invalid acct")}if(0==k&&!do_popup_actions||0==k&&f==NO_FORCE_NOHITS)verbose_log("not creating empty iframe");else if(g=LP_getloggedin(),g_dologin_clickable&&!g&&(!g_isie||g_isie&&f==FORCE_SHOW_NOHITS_NOLOGIN)){verbose_log("login state: checking whether to issue Chrome login prompt");
if(f==FORCE_SHOW_NOHITS_NOLOGIN)return;if(!g_isie){sendBG({cmd:"dologinaction"});return}}if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&LP_inIframe(window)&&LP_do_toplevel_iframe_hack(window)){(h=calculate_iframe_pos(b,j,"300px",!0))?(c=parseInt(h.posx),h=parseInt(h.posy)):h=c=0;var l=f="";try{f=window.name,l=document.location.href}catch(m){}g=b.location.href;"undefined"!=typeof punycode&&(g=punycode.URLToASCII(b.location.href));sendBG({cmd:"createpopuptoplevelfromframe",posx:c,posy:h,id:d,rows:k,
width:e,minheight:g_minheight_override,framename:f,framesrc:l,url:g})}else popupfill_create_iframe(b,c,h,d,k,e,g_minheight_override);g_popupfill_iframe_width_save=e}g_isfirefox?a?relocate_popupfill_iframes(a):relocate_popupfill_iframes(b):(!g_create_iframe_in_top||!LP_inIframe(window)||g_isie||g_isfirefox)&&relocate_popupfill_iframes(b);b=a?a:b;a=!1;if(f=getIconState(b,d))a=f.dofloater;a?change_clickable_icon_to_cancel(b,LPMAGIC+d,d):set_input_icon_image(b,j,"cancel",!0)}}
function inputHasLPBackground(b){if(null==b)return!1;var a=null;if(g_isie&&"undefined"!=typeof b.currentStyle)"undefined"!=typeof b.currentStyle&&(a=b.currentStyle);else try{a=b.ownerDocument.defaultView.getComputedStyle(b,"")}catch(d){"undefined"!=typeof b.currentStyle&&(a=b.currentStyle)}if(a&&("INPUT"==b.tagName||"input"==b.tagName)&&""!=a.backgroundImage){if(-1!=a.backgroundImage.indexOf(g_sites_light_ico)||-1!=a.backgroundImage.indexOf(g_pw_light_ico)||-1!=a.backgroundImage.indexOf(g_close_light_ico)||
-1!=a.backgroundImage.indexOf(g_ff_light_ico)||-1!=a.backgroundImage.indexOf(g_sites_ico)||-1!=a.backgroundImage.indexOf(g_pw_ico)||-1!=a.backgroundImage.indexOf(g_close_ico)||-1!=a.backgroundImage.indexOf(g_ff_ico)||-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,b,!0))||-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,b,!1)))return!0;var c;for(c=0;9>=c;c++)if(-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,b,!0,c))||-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,
b,!1,c)))return verbose_log("icon "+LP_getname(b)+" has icon with number "+c),!0}return!1}function removeLPBackground(b){if(!b)return!1;try{b.style.backgroundImage="none",b.style.backgroundRepeat="repeat",b.style.backgroundAttachment="scroll",b.style.backgroundPosition="0% 0%"}catch(a){return verbose_log("removeLPBackground error: "+a.message),!1}return!0};
