function LP_getLPIframe(a,b){a||(a=LP_derive_doc());if(!a)return null;var d=null,c=null,e;if(b&&(c=a.getElementById(b))&&"IFRAME"==c.tagName.toUpperCase()&&c.name==c.id)return c;(c=g_popupfill_parent)||(c=g_popupfill_parent_last);if(b=LP_getLPIframeID(a,c))if((c=a.getElementById(b))&&"IFRAME"==c.tagName.toUpperCase()&&c.name==c.id)return c;var g=a.getElementsByTagName("IFRAME");for(e=0;e<g.length;e++)if((c=g[e])&&"undefined"!=typeof c.id&&null!=c.id&&0==c.id.indexOf(LPMAGICIFRAME)){d=c;break}return d}
function relocate_LPIframe(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!0,d=LP_getLPIframeID(a);(d=LP_getLPIframe(a,d))?(LP_getComputedStyle(a,d),g_iframe_docked&&LP_getAbsolutePos(a,g_popupfill_parent)):b=!1;return b}function resize_LPIframe(a,b){a||(a=LP_derive_doc());if(!a||!b||"undefined"==typeof b.height||"undefined"==typeof b.width)return!1;var d=!1,c=LP_getLPIframeID(a);LP_getLPIframe(a,c)&&(d=place_LPIframe(a,b));return d}
function place_LPIframe(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=!0,c=LP_getLPIframeID(a);if(c=LP_getLPIframe(a,c)){var e=LP_getAbsolutePos(a,c);if(null===e||0>parseInt(b.width)||0>parseInt(b.height))verbose_log("invalid iframe pos"),d=!1;else{var g=parseInt(e.top)+"px",h=parseInt(e.left)+"px",m=parseInt(e.height)+"px",e=parseInt(e.width)+"px",f="";"undefined"!=typeof b.height&&(f=parseInt(b.height),""!==f&&!isNaN(f)&&(m=f+"px"));"undefined"!=typeof b.width&&(f=parseInt(b.width),""!==
f&&!isNaN(f)&&(e=f+"px"));"undefined"!=typeof b.left&&(f=parseInt(b.left),""!==f&&!isNaN(f)&&(h=f+"px"));"undefined"!=typeof b.top&&(f=parseInt(b.top),""!==f&&!isNaN(f)&&(g=f+"px"));g=sprintf("width: %s !important; height: %s !important; top: %s !important; left:%s !important;",e,m,g,h);if(""==g_frame_css_str)try{var k=document.body.getAttribute("data-lp-gcss");k&&(g_frame_css_str=LPJSON.parse(k),document.body.removeAttribute("data-lp-gcss"))}catch(l){write_error_to_history(a,"resize_LPIframe",l)}k=
g_frame_css_str+g;k.match(/position: *absolute/)||(k+=" position: absolute;");normalize_css(c.style.cssText)!=normalize_css(k)&&(c.style.cssText=k,c.setAttribute("width",e),c.setAttribute("height",m))}}else d=!1;return d}function LP_getLPIframeID(a,b){!a&&b&&(a=b.ownerDocument);a||(a=LP_derive_doc());if(!a)return null;var d=null;b?(d=LP_pickFieldName(a,b),d=LPMAGICIFRAME+d):d=void 0;return d}
function LP_computeLPIframeID(a){return"undefined"==typeof SHA256?LPMAGICIFRAME+a:SHA256(sprintf("%d-%s",Date.now(),a))}function rot13(a){if(!a)return"$str =~ tr/a-zA-Z/n-za-mN-ZA-M/";for(var b="",d=0;d<a.length;d++){var c=a.charCodeAt(d);if(65<=c&&77>=c||97<=c&&109>=c)c+=13;else if(78<=c&&90>=c||110<=c&&122>=c)c-=13;b+=String.fromCharCode(c)}return b}function LP_inIframe(a){a||(a=window);if(null==g_inframe)try{return get_win_self(a)!==a.top}catch(b){return!0}else return g_inframe}
function is_your_popup_showing(a){if(null==a)return!1;var b=!1;try{if(null==a.location){verbose_log("is_your_popup_showing given a firefox zombie document?");var d="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument;closepopupfills(d);b=!0}}catch(c){b=!0}if(b)return!1;g_isfirefox&&verbose_log("entered is_your_popup_showing for doc="+a.location.href);if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&LP_inIframe(window))return toplevel_iframe_state_get();
if(0<a.location.href.indexOf("popupfilltab.xul"))return!0;a=a.getElementsByTagName("iframe");for(b=0;b<a.length;b++)if(("function"!=typeof a.hasOwnProperty||a.hasOwnProperty(b))&&0==a[b].id.indexOf(LPMAGICIFRAME))return!0;return!1}
function enableScrollOnIframe(a,b){null==b&&(b=document?document:LP.getBrowser().contentDocument);if(null==b)return null;verbose_log("enabling Scroll on Iframe for "+b.location.href);var d=b.getElementsByTagName("IFRAME"),c,e=null;if(null!=d&&0<d.length)for(c=0;c<d.length;c++){var e=d[c],g=a.replace(/^(https:|http:)/,"");verbose_log("checking iframe src="+lp_ofa(e.src)+" passed href="+lp_ofa(a));if(e.src==a||0<e.src.indexOf(a)||0<e.src.indexOf(g))"undefined"!=typeof g_isie&&g_isie?(e.setAttribute("scrolling",
"auto"),e.style.overflow="visible",e.style.maxHeight="none"):(e.setAttribute("scrolling","auto"),e.style.overflow="auto"),verbose_log("enabling scroll on iframe to "+lp_ofa(a))}}
function enableScrollWithinIframe(a,b){null==a&&(a=document);null==b&&(b=window);if(is_your_popup_showing(a)&&get_win_self(b)!=b.top)if(verbose_log("enabling scroll on body of iframe"),g_isfirefox)a.body.style.overflow="auto";else if(g_isie){var d=0;"undefined"!=typeof init_LPfn&&(init_LPfn()&&LPfn)&&(d=LPfn.getDocumentMode(document));7<d?(a.body.style.overflow="visible",a.body.setAttribute("scroll","auto")):a.body.setAttribute("overflow","auto")}else a.body.style.overflow="auto"}
function LP_getIframeBySrc(a,b){null==a&&(a=document);var d=a.getElementsByTagName("IFRAME"),c;for(c=0;c<d.length;c++)if(d[c].src==b)return d[c];return null}function toplevelpopupsetstate_handler(a){g_create_iframe_in_top&&toplevel_iframe_state_set(a?!0:!1)}function toplevel_iframe_state_get(){return g_toplevel_iframe_exists}function toplevel_iframe_state_set(a){g_toplevel_iframe_exists=a}function LP_do_toplevel_iframe_hack(a){return!a||g_isie||g_isfirefox?!1:!0}
function relocate_popupfill_iframes(a,b){if(do_experimental_popupfill)try{var d=a;g_isfirefox&&(d="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument);if(!a||!d)return null;if(g_isfirefox&&null==a.location){verbose_log("relocate_popupfill_iframes given zombie document?");var c="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument;
closepopupfills(c)}else{var e=c=!1;if(!g){var g=a.defaultView;g||(g=a.parentWindow)}var h,m=d.getElementsByTagName("iframe");for(h=0;h<m.length;h++){var f=m[h];if("undefined"!=typeof f.id&&null!=f.id){var k=LPMAGICIFRAME;if(0==f.id.indexOf(k)){var l=f.id.substr(k.length),k=l,c=!0,n=LP_getElementByIdOrName(a,l),p=!b;if(g_isfirefox||null!=n&&lpIsVisible(n,p)){var j=null;if(g_isfirefox)j=ff_get_iframe_pos(a,g,n,k,d),null!=j&&(e=!0);else if(j=calculate_iframe_pos(a,n,0<g_minwidth_override?g_minwidth_override:
0),g_draggable&&!g_iframe_docked){var q=!0,r=LP_getAbsolutePos(a,f,q);j.posx=r.left;j.posy=r.top}null!=j&&place_iframe_absolute(a,g,f,j,d)}else g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&!LP_inIframe(g)&&toplevel_iframe_state_get()?(q=!0,j=LP_getAbsolutePos(a,f,q),j.posx=j.left,j.posy=j.top,place_iframe_absolute(a,g,f,j,d)):!g_isfirefox&&(!g_double_password_hack&&!g_double_secret_password_hack)&&closepopupfills(a)}}}g_isfirefox&&(!e&&c)&&(verbose_log("found orphan iframe, remove it"),closepopupfills(a))}}catch(s){lplog("relocate_popupfill_iframe failed, "+
s.message),do_bgiconinput||end_weasel(a),g_isfirefox&&closepopupfills(a)}}
function place_iframe_absolute(a,b,d,c,e){if(!d||!a||!b||!c)return!1;var g=null,h;if("undefined"!=typeof Math){var m=null;g_draggable&&!g_iframe_docked&&(m=LP_getComputedStyle(b,d));try{var f=c.posx,k=c.posy,l=parseInt(f)+"px",n=parseInt(k)+"px",p=0;0<parseInt(g_minwidth_override)?(p=Math.max(parseInt(g_popupfill_iframe_width_save),parseInt(g_minwidth_override))+"px",(h=LP_getWindowWidth(b,!0))&&parseInt(p)+parseInt(l)>h&&(l=h-parseInt(p)-20+"px")):0<parseInt(g_popupfill_iframe_width_save)?p=parseInt(g_popupfill_iframe_width_save)+
"px":(null==g&&(g=LP_getComputedStyle(b,d)),p=g.width);0>parseInt(l)&&(l="0px");h=0;0<parseInt(g_minheight_override)?h=Math.max(parseInt(g_popupfill_iframe_height_save),parseInt(g_minheight_override))+"px":""!=g_popupfill_iframe_height_save&&0<parseInt(g_popupfill_iframe_height_save)?h=parseInt(g_popupfill_iframe_height_save)+"px":(null==g&&(g=LP_getComputedStyle(b,d)),g&&(h=g.height));if(g_iframe_scroll_hack&&!g_frame_scrollable_set){var j=parseInt(h),q=parseInt(p),r;r=b&&"undefined"!=typeof b.getComputedStyle?
g_isfirefox?LP_getComputedStyle(b,a.documentElement):LP_getComputedStyle(b,a.body):"undefined"!=typeof a.documentElement?LP_getComputedStyle(b,a.documentElement):LP_getComputedStyle(b,a.body);parseInt(r.height);parseInt(r.width);var s=b.innerHeight,t=b.innerWidth;if(null!=j&&0<j&&null!=s&&0<s||null!=q&&0<q&&null!=t&&0<t)if((parseInt(k)+j>s||parseInt(f)+q>t)&&LP_inIframe(b)){if(g_isfirefox){enableScrollWithinIframe(a,b);var u=LP.getBrowser(),v=u?u.contentDocument:null;v&&v!=a&&enableScrollOnIframe(a.location.href,
e)}else g_isie||(verbose_log("ensuring this frame/iframe has scrolling enabled"),sendBG({cmd:"iframescrollenable",href:a.location.href}));g_frame_scrollable_set=!0}}g_draggable&&(!g_iframe_docked&&m)&&(c&&"undefined"!=typeof c.posx&&"undefined"!=typeof c.posy?(n=parseInt(c.posy)+"px",l=parseInt(c.posx)+"px",0>parseInt(c.posy)&&(n="0px"),0>parseInt(c.posx)&&(l="0px")):(n=m.top,l=m.left));place_LPIframe(a,{width:p,height:h,top:n,left:l})||(verbose_log("invalid iframe pos"),debug_checkpoint("failed to place iframe"),
closepopupfills(a))}catch(w){verbose&&alert("place_abs "+w.message)}return True}}
function normalize_css(a){a=a.replace(/ /g,"");a=a.replace(/1\.0/g,"1");a=a.replace(/2147483647/g,"2147483648");a=a.replace("border-top-style:none!important;border-right-style:none!important;border-bottom-style:none!important;border-left-style:none!important;","border-style:none!important;");g_isie&&(a=a.replace("filter:alpha(opacity=100)!important;",""),a=a.replace("border-style:none!important;",""),a=a.split(";").sort().join(";"));return a}
function moveIframe_handler(a,b){a||(a=LP_derive_doc());if(a&&g_draggable&&"undefined"!=typeof b.delx&&"undefined"!=typeof b.dely){g_iframe_docked=!1;var d=LP_getLPIframe(a);if(d){var c=LP_getAbsolutePos(a,d,!0);c&&place_iframe_absolute(document,window,d,{posx:c.left+b.delx,posy:c.top+b.dely})}}}function resizeIframe_handler(a,b){a||(a=LP_derive_doc());a&&"undefined"!=typeof b.width&&"undefined"!=typeof b.height&&resize_LPIframe(a,dims)};
