var do_bgiconinput=!0,g_CSPCHECKER=0;
function popupfill_create_iframe(a,d,e,g,b,f,h,c,j,l){if(do_experimental_popupfill&&a){c=a.getElementsByTagName("input");for(var k in c){var p=c[k];"undefined"!==typeof p.maxLength&&"password"==p.type&&(g_isie||sendBG({cmd:"set_possiblemax",max:p.maxLength}))}d=parseInt(d)+"px";e=parseInt(e)+"px";if((p=a.body)&&!a.getElementById(LPMAGICIFRAME+g)){c=a.createElement("iframe");c.id=LPMAGICIFRAME+g;c.name=LPMAGICIFRAME+g;g_iframe_docked=!0;if(g_isie)c.src="https://lastpass.com/fake/fake.php#framesrc=LPMAGIC",init_LPfn()&&
LPfn&&9>LPfn.getDocumentMode(a)&&(c.setAttribute("allowTransparency",!0),c.setAttribute("frameBorder",0),c.allowTransparency=!0,c.frameBorder=0);else if("undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk){g_popup_iframe=c;add_event_listener_if();var m=a.location.href,m=lpParseUri(m),t=Math.floor(1E8*Math.random());c.setAttribute("lpsrc",m.protocol+"://"+t+"."+m.host+"/lpblankiframe.local")}else m=urlprefix+"popupfilltab.html","undefined"===typeof chrome&&"undefined"!=typeof lplanguage&&(m+="?lplanguage="+
lplanguage),c.src=m;0>parseInt(d)&&(d="0px");0>parseInt(e)&&(e="0px");dotrans?(g_frame_css_str="display:block; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:none !important; opacity: 1.0 !important;","undefined"!=typeof g_isie&&g_isie&&(g_frame_css_str+="background-color:transparent !important;background-image:none !important;filter:alpha(opacity=100) !important ; ")):g_frame_css_str="display:block; position:absolute !important; visibility:visible !important; opacity: 1.0 !important ; z-index:"+
CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); filter:alpha(opacity=100) !important; ";c.style.cssText=g_frame_css_str;try{if(framesetarr=document.getElementsByTagName("frameset"),0==framesetarr.length)p.appendChild(c);
else if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&j&&1==framesetarr.length){var n=LPJSON.stringify(g_frame_css_str+" border: none;");j.body.setAttribute("data-lp-gcss",n);var q=j.getElementsByTagName("FRAMESET");if(q&&q[0]){var r=q[0].getElementsByTagName("FRAME");if(r){var s=r[0].contentWindow.document;s.body.setAttribute("data-lp-gcss",n);s.body.appendChild(c)}else j.body.appendChild(c)}}else{j=!1;for(k=0;k<framesetarr.length;k++){for(n=0;n<framesetarr[k].children.length;n++)if("FRAME"==framesetarr[k].children[n].tagName)if(cf=
framesetarr[k].children[n].contentWindow.document,null!=cf.getElementById(g)){if(j=!0,toappendTo=cf.getElementById(g),l&&l.framesrc&&l.framesrc==get_doc_location_href(cf))break}else if(null!=cf.getElementsByName(g)&&0!=cf.getElementsByName(g).length&&(j=!0,toappendTo=cf.getElementsByName(g)[0],l&&l.framesrc&&l.framesrc==get_doc_location_href(cf)))break;if(j){try{toappendTo.ownerDocument.body.setAttribute("data-lp-gcss",LPJSON.stringify(g_frame_css_str)),toappendTo.parentNode.appendChild(c)}catch(v){framesetarr[k].children[n].contentWindow.document.body.appendChild(c)}break}}}}catch(u){verbose_log("append failed! "+
u);return}g_isie&&!LP_getloggedin()&&c.parentNode.removeChild(c);c.width=parseInt(f)+"px";c.height=g_isie?"38px":"26px";"undefined"!=typeof b&&0<b&&(c.height=24*b+23+"px");c.height=0<parseInt(h)?parseInt(h)+"px":parseInt(c.height)+"px";g=parseInt(c.width)+"px";b=parseInt(c.height)+"px";c.style.cssText=g_frame_css_str+("width: "+g+" !important; height: "+b+" !important; top:"+e+" !important; left:"+d+" !important; ");setTimeout(function(){0==g_CSPCHECKER&&("undefined"===typeof chrome&&"object"===typeof safari)&&
do_iframe_sad_msg(a)},5E3)}}}function weasel(a){LPCTR("weasel");if(do_experimental_popupfill){if("undefined"==typeof a||!1==a||!0==a||5>a)a=200;g_weaseled=!0;if(g_isdebug){var d=(new Date).getTime(),e=d-g_last_weasel;e>2*a&&verbose_log("last weasel cycle took too long"+e+" ms")}popupfill_resize();g_isdebug&&(d=(new Date).getTime()-d,d>a&&verbose_log("last resize took too long "+d+" ms"),g_last_weasel=(new Date).getTime());g_weasel_id=setTimeout(function(){weasel(a)},a)}}var g_last_weasel=0;
function issaveall(a){a=a.elements;for(var d=0,e=0,g=0,b=0;b<a.length;b++){var f=a[b].type;"password"==f?e++:"text"==f||"tel"==f||"email"==f?d++:"textarea"==f&&g++}return 1==d&&1==e&&0==g?!1:!0}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,d,e,g){if(!do_experimental_popupfill)return null;"undefined"==typeof g&&(g=!1);if(!a||null==d)return null;var b=d.style.left,f=d.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(b)||0>parseInt(f)){var h=a.getElementById(LPMAGICIFRAME+LP_pickFieldName(a,d));if(null!=h&&(h=LP_getAbsolutePos(a,h,null,g)))return f=parseInt(h.top),b=parseInt(h.left),isNaN(f)||isNaN(b)?null:{posx:b+"px",posy:f+"px"}}LP_pickFieldName(a,d);if(null!=d){h=LP_getAbsolutePos(a,
d,null,g);null!=h&&(b=parseInt(h.left)+POPUP_FIELD_OFFSET+"px",f=parseInt(h.top)+parseInt(h.height)+"px",g_do_icon_number_hint&&(f=parseInt(h.top)+parseInt(h.height)+4+"px"));if(null==e||0==e||""==e)h=LP_getElementByIdOrName(a,LPMAGICIFRAME+LP_pickFieldName(a,d)),e=null!=h?(e=LP_getAbsolutePos(a,h,null,!0))?e.width:0:0;if(!g){g=LP_getWindowWidth(window,!0);if(!g)return{posx:0,posy:0};parseInt(e)+parseInt(b)>g&&(b=g-parseInt(e)-20+"px")}}if(""==b||"auto"==b||""==f||"auto"==f)return null;b=parseInt(b);
f=parseInt(f);return"NaN"==b||"NaN"==f?null:{posx:b+"px",posy:f+"px"}}function verbose_log(a){verbose&&("undefined"!=typeof Date?console_log((new Date).getTime()-g_tsstart+" : "+a):console_log(a))}function is_watermark(){return!1}function checkAskGenerate(){}function sendKey(a,d){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(d,0,KeyEvent[keyName],!1)}catch(e){lpdbg("error",e)}return null}
function send_simulated_key(a,d,e,g){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;var b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keydown",!0,!0,null,!1,!1,g,!1,e,d):b.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,g,!1,e,e);var f=a.dispatchEvent(b);f&&("undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk)&&(b=a.ownerDocument.createEvent("KeyboardEvent"),b.initKeyEvent("keypress",
!0,!0,null,!1,!1,g,!1,e,d),f=a.dispatchEvent(b));b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keyup",!0,!0,null,!1,!1,g,!1,e,d):b.initKeyboardEvent("keyup",!0,!0,null,!1,!1,g,!1,e,e);a.dispatchEvent(b);return f}var g_formmutations=0;
function checkShouldRecheck(){if(!(20<g_formmutations)&&do_experimental_popupfill&&0<=g_input_cnt&&0<=g_form_cnt){var a=countInputs(document),d=countFormEquivalents(document),e=computeFingerprint(document);verbose_log("checkShouldRecheck() : # inputs was "+g_input_cnt+", now "+a+" #forms was "+g_form_cnt+" now "+d+", fingerprint was "+g_input_fingerprint+" now "+e);if(g_input_cnt!=a||g_form_cnt!=d||g_input_fingerprint!=e)g_formmutations++,formcachereset(document),fieldcachereset(document),g_isie?
(setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},200),setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3)):setTimeout(function(){LPCTR("recheck");evalScriptsInFrame(window,document,!0)},200),g_input_cnt=a,g_form_cnt=d,g_input_fingerprint=e}}function is_watermark_password(){return!1}
function createpopuptoplevel_handler(a){var d=LP_derive_doc(),e=parseInt(a.from_iframe.posx),g=parseInt(a.from_iframe.posy),b=a.from_iframe.id,f=a.from_iframe.rows,h=a.from_iframe.width,c=a.from_iframe.framename,j=a.from_iframe.framesrc,l=null;if(!is_your_popup_showing(d)){var k=find_iframe_pos(d,c,j,!1);k||(k=find_iframe_pos(d,c,j,!0),null!==k&&"undefined"!=typeof k.cframedoc&&(l=k.cframedoc));j=c=0;k?(c=parseInt(k.left)+e+"px",j=parseInt(k.top)+g+"px",g_toplevel_initial_abs_x=c,g_toplevel_initial_abs_y=
j):j=c="10px";popupfill_create_iframe(d,c,j,b,f,h,"90px",!1,l,a.from_iframe);g_popupfill_iframe_width_save=h}}var g_toplevel_initial_abs_x=null,g_toplevel_initial_abs_y=null;function popupfillresize_handler(a){0<a.width&&(g_minwidth_override=parseInt(a.width));0<a.height&&(g_minheight_override=parseInt(a.height));g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&!LP_inIframe(window)&&toplevel_iframe_state_get()&&relocate_popupfill_iframes(document)}
function find_iframe_pos(a,d,e,g){if(!a)return null;var b,f;try{var h=a.getElementsByTagName("IFRAME");g&&(h=a.getElementsByTagName("FRAME"));if(!d&&1==h.length)return LP_getAbsolutePos(a,h[0],!0,!0);var c=[];for(b=0;b<h.length&&50>b;b++)c[b]=h[b];for(b=0;b<c.length;b++)if(c[b].name&&""!=d&&c[b].name==d||c[b].src&&""!=e&&c[b].src==e)return LP_getAbsolutePos(a,c[b],!0,!0);if(g)for(b=0;b<c.length;b++){var j=c[b].contentWindow.document,l=j.getElementsByTagName("FRAME");for(f=0;f<l.length&&50>f;f++)if(l[f].name&&
""!=d&&l[f].name==d||l[f].src&&""!=e&&l[f].src==e){var k=LP_getAbsolutePos(j,l[f],!0,!0);k.cframedoc=j;return k}}}catch(p){}return null};
