document.title=gs("Preferences");document.getElementById("lp_docwrite_prefs2")&&(document.getElementById("lp_docwrite_prefs2").innerHTML=gs("Security"));document.getElementById("lp_docwrite_prefs3")&&(document.getElementById("lp_docwrite_prefs3").innerHTML=gs("Disable Chrome Password Manager"));
document.getElementById("lp_docwrite_prefs4")&&(document.getElementById("lp_docwrite_prefs4").innerHTML="<label for='logoffWhenCloseBrowser'>"+gs("Automatically Log out when all browsers are closed and Chrome has been closed for (mins)")+"</label>");document.getElementById("lp_docwrite_prefs5")&&(document.getElementById("lp_docwrite_prefs5").innerHTML="<label for='idleLogoffEnabled'>"+gs("Automatically Log out after idle (mins)")+"</label>");
document.getElementById("lp_docwrite_prefs6")&&(document.getElementById("lp_docwrite_prefs6").innerHTML=gs("Install the binary version of LastPass for Chrome to enable automatic log out after idle"));document.getElementById("lp_docwrite_prefs7")&&(document.getElementById("lp_docwrite_prefs7").innerHTML=gs("Install the LastPass Library for Chrome to enable automatic log out after idle"));document.getElementById("lp_docwrite_prefs8")&&(document.getElementById("lp_docwrite_prefs8").innerHTML=gs("General"));
document.getElementById("lp_docwrite_prefs9")&&(document.getElementById("lp_docwrite_prefs9").innerHTML=gs("Open New Pages in"));document.getElementById("lp_docwrite_prefs10")&&(document.getElementById("lp_docwrite_prefs10").innerHTML=gs("the current tab"));document.getElementById("lp_docwrite_prefs11")&&(document.getElementById("lp_docwrite_prefs11").innerHTML=gs("Tabs"));document.getElementById("lp_docwrite_prefs12")&&(document.getElementById("lp_docwrite_prefs12").innerHTML=gs("Windows"));
document.getElementById("lp_docwrite_prefs13")&&(document.getElementById("lp_docwrite_prefs13").innerHTML="<label for='highlightFields'>"+gs("Highlight input boxes")+"</label>");document.getElementById("lp_docwrite_prefs14")&&(document.getElementById("lp_docwrite_prefs14").innerHTML="<label for='automaticallyFill'>"+gs("Automatically Fill Login Information")+"</label>");
document.getElementById("lp_docwrite_prefs15")&&(document.getElementById("lp_docwrite_prefs15").innerHTML="<label for='showvault'>"+gs("Show My LastPass Vault After Login")+"</label>");document.getElementById("lp_docwrite_prefs16")&&(document.getElementById("lp_docwrite_prefs16").innerHTML=gs("Appearance"));document.getElementById("lp_docwrite_prefs17")&&(document.getElementById("lp_docwrite_prefs17").innerHTML="<label for='showAcctsInGroups'>"+gs("Show Sites in Groups")+"</label>");
document.getElementById("lp_docwrite_prefs18")&&(document.getElementById("lp_docwrite_prefs18").innerHTML="<label for='hideContextMenus'>"+gs("Hide Context Menu Options")+"</label>");document.getElementById("lp_docwrite_prefs19")&&(document.getElementById("lp_docwrite_prefs19").innerHTML=gs("Form Fill"));document.getElementById("lp_docwrite_prefs20")&&(document.getElementById("lp_docwrite_prefs20").innerHTML=gs("Default Form Fill Profile"));
document.getElementById("lp_docwrite_prefs21")&&(document.getElementById("lp_docwrite_prefs21").innerHTML="<label for='donotoverwritefilledfields'>"+gs("Do not overwrite fields that are already filled")+"</label>");document.getElementById("lp_docwrite_prefs22")&&(document.getElementById("lp_docwrite_prefs22").innerHTML=gs("Notifications"));
document.getElementById("lp_docwrite_prefs23")&&(document.getElementById("lp_docwrite_prefs23").innerHTML="<label for='showNotifications'>"+gs("Show Notifications")+"&nbsp;"+gs("_Chrome_Only_Toolstrip_")+"</label>");document.getElementById("lp_docwrite_prefs24")&&(document.getElementById("lp_docwrite_prefs24").innerHTML="<label for='showGenerateNotifications'>"+gs("Offer to Generate Secure Passwords")+"</label>");
document.getElementById("lp_docwrite_prefs25")&&(document.getElementById("lp_docwrite_prefs25").innerHTML="<label for='showFormFillNotifications'>"+gs("Show Form Fill Notifications")+"</label>");document.getElementById("lp_docwrite_prefs26")&&(document.getElementById("lp_docwrite_prefs26").innerHTML="<label for='showSaveSiteNotifications'>"+gs("Show Save Site Notifications")+"&nbsp;"+gs("_Chrome_Only_Toolstrip_")+"</label>");
document.getElementById("lp_docwrite_prefs27")&&(document.getElementById("lp_docwrite_prefs27").innerHTML="<label for='showNotificationsAfterClick'>"+gs("Show certain notifications only after click")+"</label>");document.getElementById("lp_docwrite_prefs28")&&(document.getElementById("lp_docwrite_prefs28").innerHTML="<label for='showFillNotificationBar'>"+gs("Show Fill Notification Bar")+"</label>");
document.getElementById("lp_docwrite_prefs29")&&(document.getElementById("lp_docwrite_prefs29").innerHTML="<label for='showSaveNotificationBar'>"+gs("Show Save Site Notification Bar")+"</label>");document.getElementById("lp_docwrite_prefs30")&&(document.getElementById("lp_docwrite_prefs30").innerHTML="<label for='showChangeNotificationBar'>"+gs("Show Change Password Notification Bar")+"</label>");
document.getElementById("lp_docwrite_prefs31")&&(document.getElementById("lp_docwrite_prefs31").innerHTML=gs("Feedback"));document.getElementById("lp_docwrite_prefs32")&&(document.getElementById("lp_docwrite_prefs32").innerHTML=gs("Click here to launch feedback"));document.getElementById("lp_docwrite_prefs33")&&(document.getElementById("lp_docwrite_prefs33").innerHTML=gs("HotKeys"));document.getElementById("lp_docwrite_prefs34")&&(document.getElementById("lp_docwrite_prefs34").innerHTML=gs("Generate Secure Password"));
document.getElementById("lp_docwrite_prefs35")&&(document.getElementById("lp_docwrite_prefs35").innerHTML=gs("Recheck Page"));document.getElementById("lp_docwrite_prefs36")&&(document.getElementById("lp_docwrite_prefs36").innerHTML=gs("Site Search"));document.getElementById("lp_docwrite_prefs37")&&(document.getElementById("lp_docwrite_prefs37").innerHTML=gs("Fill In Next Login (When Multiple)"));
document.getElementById("lp_docwrite_prefs38")&&(document.getElementById("lp_docwrite_prefs38").innerHTML=gs("Fill In Previous Login (When Multiple)"));document.getElementById("lp_docwrite_prefs39")&&(document.getElementById("lp_docwrite_prefs39").innerHTML=gs("Submit Form"));document.getElementById("lp_docwrite_prefs40")&&(document.getElementById("lp_docwrite_prefs40").innerHTML=gs("Open My LastPass Vault"));
document.getElementById("lp_docwrite_prefs41")&&(document.getElementById("lp_docwrite_prefs41").innerHTML=gs("Save All Entered Data"));document.getElementById("lp_docwrite_prefs42")&&(document.getElementById("lp_docwrite_prefs42").innerHTML=gs("Log Out"));document.getElementById("lp_docwrite_prefs43")&&(document.getElementById("lp_docwrite_prefs43").innerHTML=gs("Fill In Default Form Fill Profile"));
document.getElementById("lp_docwrite_prefs44")&&(document.getElementById("lp_docwrite_prefs44").innerHTML=gs("Open Popover"));document.getElementById("lp_docwrite_prefs45")&&(document.getElementById("lp_docwrite_prefs45").innerHTML=gs("Account Settings"));document.getElementById("lp_docwrite_prefs46")&&(document.getElementById("lp_docwrite_prefs46").innerHTML=gs("Click here to launch account settings"));
document.getElementById("lp_docwrite_prefs47")&&(document.getElementById("lp_docwrite_prefs47").innerHTML=gs("Require security reprompt when:"));document.getElementById("lp_docwrite_prefs48")&&(document.getElementById("lp_docwrite_prefs48").innerHTML=gs("Log into a Site"));document.getElementById("lp_docwrite_prefs49")&&(document.getElementById("lp_docwrite_prefs49").innerHTML=gs("Edit Site"));
document.getElementById("lp_docwrite_prefs50")&&(document.getElementById("lp_docwrite_prefs50").innerHTML=gs("Edit Secure Notes"));document.getElementById("lp_docwrite_prefs51")&&(document.getElementById("lp_docwrite_prefs51").innerHTML=gs("View Passwords"));document.getElementById("lp_docwrite_prefs52")&&(document.getElementById("lp_docwrite_prefs52").innerHTML=gs("Fill or Edit Form Fill Data"));
document.getElementById("lp_docwrite_prefs53")&&(document.getElementById("lp_docwrite_prefs53").innerHTML=gs("Advanced"));document.getElementById("lp_docwrite_prefs54")&&(document.getElementById("lp_docwrite_prefs54").innerHTML=gs("Automatically login to sites if time since last login > (seconds)"));document.getElementById("lp_docwrite_prefs55")&&(document.getElementById("lp_docwrite_prefs55").innerHTML="<label for='warninsecureforms'>"+gs("Warn before filling insecure forms")+"</label>");
document.getElementById("lp_docwrite_prefs56")&&(document.getElementById("lp_docwrite_prefs56").innerHTML="<label for='dontfillautocompleteoff'>"+gs("Respect AutoComplete=off: allow websites to disable AutoFill")+"</label>");document.getElementById("lp_docwrite_prefs57")&&(document.getElementById("lp_docwrite_prefs57").innerHTML=gs("Poll Server for account changes (mins)"));
document.getElementById("lp_docwrite_prefs58")&&(document.getElementById("lp_docwrite_prefs58").innerHTML="<label for='clearClipboardSecsEnabled'>"+gs("Clear Clipboard after use (seconds)")+"</label>");document.getElementById("lp_docwrite_prefs59")&&(document.getElementById("lp_docwrite_prefs59").innerHTML="<label for='recentUsed'>"+gs("Recently Used list size")+"</label>");
document.getElementById("lp_docwrite_prefs60")&&(document.getElementById("lp_docwrite_prefs60").innerHTML="<label for='searchNotes'>"+gs("Search within secure notes")+"</label>");document.getElementById("lp_docwrite_prefs61")&&(document.getElementById("lp_docwrite_prefs61").innerHTML="<label for='openloginstart'>"+gs("Open login dialog when browser starts")+"</label>");
document.getElementById("lp_docwrite_prefs62")&&(document.getElementById("lp_docwrite_prefs62").innerHTML="<label for='storeLostOTP'>"+gs("Save a disabled One Time Password locally for Account Recovery")+"</label>");document.getElementById("lp_docwrite_prefs63")&&(document.getElementById("lp_docwrite_prefs63").innerHTML="<label for='enablenamedpipes'>"+gs("Share login state between other browsers")+"</label>");
document.getElementById("lp_docwrite_prefs64")&&(document.getElementById("lp_docwrite_prefs64").innerHTML=gs("Install the binary version of LastPass for Chrome to enable sharing login state between other browsers"));document.getElementById("lp_docwrite_prefs65")&&(document.getElementById("lp_docwrite_prefs65").innerHTML=gs("Language"));
document.getElementById("lp_docwrite_prefs66")&&(document.getElementById("lp_docwrite_prefs66").innerHTML="<label for='enablenewlogin'>"+gs("Enable new login screen")+"</label>");document.getElementById("lp_docwrite_prefs67")&&(document.getElementById("lp_docwrite_prefs67").innerHTML=gs("This can only be handled from a webpage"));
document.getElementById("lp_docwrite_prefs68")&&(document.getElementById("lp_docwrite_prefs68").innerHTML="<label for='clearfilledfieldsonlogoff'>"+gs("Clear filled fields on log out")+"</label>");document.getElementById("lp_docwrite_prefs168")&&(document.getElementById("lp_docwrite_prefs168").innerHTML="<label for='toplevelmatchingsites'>"+gs("Show Matching Sites in top level menu")+"</label>");
document.getElementById("lp_docwrite_prefs170")&&(document.getElementById("lp_docwrite_prefs170").innerHTML="<label for='htmlindialog'>"+gs("Open extension pages in dialogs")+"</label>");document.getElementById("lp_docwrite_prefs69")&&(document.getElementById("lp_docwrite_prefs69").innerHTML="<label for='usepopupfill'>"+gs("Click Icons in Fields")+"</label>");
document.getElementById("lp_docwrite_prefs169")&&(document.getElementById("lp_docwrite_prefs169").innerHTML="<label for='showmatchingbadge'>"+gs("Show Matching Sites Count in Toolbar")+"</label>");document.getElementById("lp_docwrite_prefs70")&&(document.getElementById("lp_docwrite_prefs70").innerHTML=gs("Icons"));document.getElementById("lp_docwrite_prefs71")&&(document.getElementById("lp_docwrite_prefs71").innerHTML="<label for='notificationsBottom'>"+gs("Show notifications below browser")+"</label>");
document.addEventListener("DOMContentLoaded",function(){window.addEventListener("load",function(){onLoad()});document.getElementById("prefs").onsubmit=function(){return!1};document.getElementById("getbinary1").onclick=function(){getbinary();return!1};document.getElementById("getbinary2").onclick=function(){getbinary();return!1};document.getElementById("generateHk").onkeypress=function(){return!1};document.getElementById("generateHk").addEventListener("keyup",function(a){fixhk("generateHk",a)});document.getElementById("generateHk").addEventListener("blur",
function(a){fixhk("generateHk",a)});document.getElementById("generateHk").addEventListener("keydown",function(a){capturehk("generateHk",a)});document.getElementById("recheckHk").onkeypress=function(){return!1};document.getElementById("recheckHk").addEventListener("keyup",function(a){fixhk("recheckHk",a)});document.getElementById("recheckHk").addEventListener("blur",function(a){fixhk("recheckHk",a)});document.getElementById("recheckHk").addEventListener("keydown",function(a){capturehk("recheckHk",
a)});document.getElementById("searchHk").onkeypress=function(){return!1};document.getElementById("searchHk").addEventListener("keyup",function(a){fixhk("searchHk",a)});document.getElementById("searchHk").addEventListener("blur",function(a){fixhk("searchHk",a)});document.getElementById("searchHk").addEventListener("keydown",function(a){capturehk("searchHk",a)});document.getElementById("nextHk").onkeypress=function(){return!1};document.getElementById("nextHk").addEventListener("keyup",function(a){fixhk("nextHk",
a)});document.getElementById("nextHk").addEventListener("blur",function(a){fixhk("nextHk",a)});document.getElementById("nextHk").addEventListener("keydown",function(a){capturehk("nextHk",a)});document.getElementById("prevHk").onkeypress=function(){return!1};document.getElementById("prevHk").addEventListener("keyup",function(a){fixhk("prevHk",a)});document.getElementById("prevHk").addEventListener("blur",function(a){fixhk("prevHk",a)});document.getElementById("prevHk").addEventListener("keydown",function(a){capturehk("prevHk",
a)});document.getElementById("submitHk").onkeypress=function(){return!1};document.getElementById("submitHk").addEventListener("keyup",function(a){fixhk("submitHk",a)});document.getElementById("submitHk").addEventListener("blur",function(a){fixhk("submitHk",a)});document.getElementById("submitHk").addEventListener("keydown",function(a){capturehk("submitHk",a)});document.getElementById("homeHk").onkeypress=function(){return!1};document.getElementById("homeHk").addEventListener("keyup",function(a){fixhk("homeHk",
a)});document.getElementById("homeHk").addEventListener("blur",function(a){fixhk("homeHk",a)});document.getElementById("homeHk").addEventListener("keydown",function(a){capturehk("homeHk",a)});document.getElementById("saveallHk").onkeypress=function(){return!1};document.getElementById("saveallHk").addEventListener("keyup",function(a){fixhk("saveallHk",a)});document.getElementById("saveallHk").addEventListener("blur",function(a){fixhk("saveallHk",a)});document.getElementById("saveallHk").addEventListener("keydown",
function(a){capturehk("saveallHk",a)});document.getElementById("logoffHk").onkeypress=function(){return!1};document.getElementById("logoffHk").addEventListener("keyup",function(a){fixhk("logoffHk",a)});document.getElementById("logoffHk").addEventListener("blur",function(a){fixhk("logoffHk",a)});document.getElementById("logoffHk").addEventListener("keydown",function(a){capturehk("logoffHk",a)});document.getElementById("defaultffidHk").onkeypress=function(){return!1};document.getElementById("defaultffidHk").addEventListener("keyup",
function(a){fixhk("defaultffidHk",a)});document.getElementById("defaultffidHk").addEventListener("blur",function(a){fixhk("defaultffidHk",a)});document.getElementById("defaultffidHk").addEventListener("keydown",function(a){capturehk("defaultffidHk",a)});document.getElementById("openpopoverHk").onkeypress=function(){return!1};document.getElementById("openpopoverHk").addEventListener("keyup",function(a){fixhk("openpopoverHk",a)});document.getElementById("openpopoverHk").addEventListener("blur",function(a){fixhk("openpopoverHk",
a)});document.getElementById("openpopoverHk").addEventListener("keydown",function(a){capturehk("openpopoverHk",a)});document.getElementById("launchaccountsettings").onclick=function(){openaccountsettings();return!1};document.getElementById("getbinary3").onclick=function(){getbinary();return!1};document.getElementById("language").onclick=function(){return g_ischrome?(showChromeLanguageError(),!1):!0};document.getElementById("helptranslate").addEventListener("click",function(){openhelptranslate();return!1});
document.getElementById("save").addEventListener("click",function(){dosave();return!1});document.getElementById("default").addEventListener("click",function(){dodefault();return!1});document.getElementById("cancel").addEventListener("click",function(){docancel();return!1});document.getElementById("notifications_help").addEventListener("click",function(){openhelp("notifications");return!1});document.getElementById("hotkeys_help").addEventListener("click",function(){openhelp("hotkeys");return!1});document.getElementById("general_help").addEventListener("click",
function(){openhelp("security");return!1});document.getElementById("general2_help").addEventListener("click",function(){openhelp("general");return!1});document.getElementById("general3_help").addEventListener("click",function(){openhelp("appearance");return!1});document.getElementById("general4_help").addEventListener("click",function(){openhelp("formfill");return!1});document.getElementById("advanced_help").addEventListener("click",function(){openhelp("advanced");return!1})});
g_ismaxthon&&(document.getElementById("openpref").options[2]=null);is_in_dialog()&&(document.getElementById("body").style.padding="10px 0px");
