var tabnames="treepane ffpane identpane sharepane credmonpane entpane videopane".split(" "),g_activetab=null,g_lasttab="",g_partnername="";this.inittabs=function(){g_activetab=document.getElementById("sites");g_activetab.className+=" activetab"};
this.ontabchange=function(b){for(var a=0;a<tabnames.length;a++)document.getElementById(tabnames[a])&&(document.getElementById(tabnames[a]).style.display="none",g_activetab&&(g_activetab.className=trim(g_activetab.className.replace("activetab",""))));a=document.getElementById("q")?document.getElementById("q"):document.getElementById("lpsearchstr");""!=g_lasttab&&a&&(""!=a.value&&"undefined"!=typeof maintabs)&&(a.value="",SearchTree(g_lasttab));a=b.getAttribute("tabid");document.getElementById(tabnames[a]).style.display=
"block";g_lasttab=b.id;g_activetab=b;g_activetab.className+=" activetab";document.getElementById("expandcollapse")&&(document.getElementById("expandcollapse").style.display="0"==a?"":"none");document.getElementById("creategrouprow")&&(document.getElementById("creategrouprow").style.display="0"==a?"":"none");"sites"==g_lasttab&&"function"==typeof fix_nosites&&fix_nosites();"ff"==g_lasttab&&populateff("");"ident"==g_lasttab&&populateident("");"shares"==g_lasttab&&"function"==typeof populateshares_remote&&
populateshares_remote();"credmon"==g_lasttab&&populatealerts("");"enterprise"==g_lasttab&&loadenterprise();"video"==g_lasttab?loadvideo():hidevideo();updateActionMenu(a)};
this.updateActionMenu=function(b){if(-1==window.location.href.indexOf("showdeleted")){var a="Add Site;Add Profile;Add Identity;;Add Profile;;".split(";");document.getElementById("addsite").style.display="   none  none none none".split(" ")[b];document.getElementById("addsecurenote").style.display=" none none none none none none none".split(" ")[b];document.getElementById("addsitetext").innerHTML="undefined"!=typeof translations[a[b]]?translations[a[b]]:a[b];document.getElementById("actions_separator")&&
(document.getElementById("actions_separator").style.display="none"==document.getElementById("addsite").style.display&&"none"==document.getElementById("addsecurenote").style.display&&"none"==document.getElementById("creategrouprow").style.display?"none":"block")}};this.geturltoload=function(b){b=("undefined"!=typeof baseurl?baseurl:"")+b;""!=g_partnername&&(b+=(0<=b.indexOf("?")?"&":"?")+"partnername="+encodeURIComponent(g_partnername));return b.replace("?&","?")};
this.loadenterprise=function(){var b=document.getElementById("entpane");if(!document.getElementById("entiframe")){var a=document.createElement("iframe");a.id="entiframe";a.type="content";a.className="overviewiframe";a.setAttribute("src",geturltoload("enterprise_overview2.php"));b.appendChild(a)}};
this.loadvideo=function(){var b=document.getElementById("videopane");if(!document.getElementById("videoiframe")){var a=document.createElement("iframe");a.id="videoiframe";a.type="content";a.className="overviewiframe";a.setAttribute("src",geturltoload("video_overview.php"));b.appendChild(a)}};this.hidevideo=function(){try{var b=document.getElementById("videoiframe");if(b){var a=document.getElementById("videopane");a&&b.parentNode==a&&a.removeChild(b)}}catch(e){}};
this.populateffcommon=function(b,a){var e="undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl,g=document.getElementById("ffpane");if(0==b.length&&"undefined"==typeof g_no_overview){if(!document.getElementById("ffiframe")){for(;g.children.length;)g.removeChild(g.children[0]);e=document.createElement("iframe");e.id="ffiframe";e.type="content";e.className="overviewiframe";e.setAttribute("src",geturltoload("formfill_overview.php"));e.setAttribute("frameborder","0");g.appendChild(e)}}else{for(;g.children.length;)g.removeChild(g.children[0]);
a=a.toLowerCase();var l=document.createElement("table");l.className="vault-table";for(var h={},f=0;f<b.length;f++){var c=b[f],m="string"==typeof c.decprofilename?c.decprofilename:c.profilename;if(!(""!=a&&-1==m.indexOf(a))){var k=document.createElement("tr");k.className="table-row";var j=document.createElement("td"),d=document.createElement("td");0==f?(j.className+=" firstrowleft",d.className+=" firstrowright"):f==b.length-1&&(j.className+=" lastrowleft",d.className+=" lastrowright");d.align="right";
j.innerHTML="<a href='#' id='launchffid"+of(c.ffid)+"'><img src='"+e+"images/vaultff.png' class='border0px'/>"+of(m)+"</a>";h["launchffid"+c.ffid]=function(){openff(this.id.substring(10));return!1};d.innerHTML="<a href='#' id='editffid"+of(c.ffid)+"' title='"+gs("Edit")+"'><img src='"+e+"images/vaultedit.png' class='border0px'/></a> | ";h["editffid"+c.ffid]=function(){openff(this.id.substring(8));return!1};"undefined"==typeof g_hideprofilecopy&&(d.innerHTML+="<a href='#' id='copyffid"+of(c.ffid)+
"' title='"+gs("Copy")+"'><img src='"+e+"images/vaultcopy.png' class='border0px'/></a> | ",h["copyffid"+c.ffid]=function(){copyff(this.id.substring(8));return!1});d.innerHTML+="<a href='#' id='deleteffid"+of(c.ffid)+"' title='"+gs("Delete")+"'><img src='"+e+"images/vaultdelete.png' class='border0px'/></a>";h["deleteffid"+c.ffid]=function(){delff(this.id.substring(10));return!1};k.appendChild(j);k.appendChild(d);l.appendChild(k)}}g.appendChild(l);for(f in h)document.getElementById(f).onclick=h[f]}};
function populateidentcommon(b,a){for(var e=document.getElementById("identpane");e.children.length;)e.removeChild(e.children[0]);var g="undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl;a=a.toLowerCase();var l=document.createElement("table");l.className="vault-table";for(var h={},f=0;f<b.length;f++){var c=b[f],m="string"==typeof c.deciname?c.deciname:c.iname;if(!(""!=a&&-1==m.indexOf(a))){var k=document.createElement("tr");k.className="table-row";var j=document.createElement("td"),d=document.createElement("td");
0==f?(j.className+=" firstrowleft",d.className+=" firstrowright"):f==b.length-1&&(j.className+=" lastrowleft",d.className+=" lastrowright");d.align="right";j.innerHTML="<a href='#' id='launchident"+of(c.iid)+"'><img src='"+g+"images/vaultidentity.png' class='border0px'/>"+of(m)+"</a>";h["launchident"+c.iid]=function(){openident(this.id.substring(11));return!1};d.innerHTML="<a href='#' id='editident"+of(c.iid)+"' title='"+gs("Edit")+"'><img src='"+g+"images/vaultedit.png' class='border0px'/></a> | ";
h["editident"+c.iid]=function(){openident(this.id.substring(9));return!1};"undefined"==typeof g_hideidentcopy&&(d.innerHTML+="<a href='#' id='copyident"+of(c.iid)+"' title='"+gs("Copy")+"'><img src='"+g+"images/vaultcopy.png' class='border0px'/></a> | ",h["copyident"+c.iid]=function(){copyident(this.id.substring(9));return!1});d.innerHTML+="<a href='#' id='deleteident"+of(c.iid)+"' title='"+gs("Delete")+"'><img src='"+g+"images/vaultdelete.png' class='border0px'/></a>";h["deleteident"+c.iid]=function(){delident(this.id.substring(11));
return!1};k.appendChild(j);k.appendChild(d);l.appendChild(k)}}e.appendChild(l);for(f in h)document.getElementById(f).onclick=h[f]}function cleariframe(b){try{if(document.getElementById(b))for(;document.getElementById(b).children.length;)document.getElementById(b).removeChild(document.getElementById(b).children[0])}catch(a){}};
