function LP_getElementByXPath(a,b){return!a&&(a=LP_derive_doc(),!a)?null:LP_lookupElementByXPath(a,b)}function LP_getElementsByXPath(a,b){return!a&&(a=LP_derive_doc(),!a)?null:LP_lookupElementsByXPath(a,b)}
function LP_createXPathFromElement(a,b){if(!a&&(a=LP_derive_doc(),!a)||!b)return null;var e=a.getElementsByTagName("*"),d,c;if(0<e.length&&("undefined"==typeof e[0].hasAttribute||"undefined"==typeof e[0].localName))return LP_getXPath(b);for(segs=[];b&&1==b.nodeType;b=b.parentNode)if(b.hasAttribute("id")){for(c=d=0;c<e.length&&!(e[c].hasAttribute("id")&&e[c].id==b.id&&d++,1<d);c++);if(1==d)return segs.unshift('id("'+b.getAttribute("id")+'")'),segs.join("/");d=b.parentNode?b.parentNode.children:[];
for(var f=c=0;f<d.length&&!("undefined"!=typeof d[f].hasAttribute&&(d[f].hasAttribute("id")&&d[f].id==b.id)&&c++,1<c);f++);if(1<c){d=1;for(c=b.previousSibling;c;c=c.previousSibling)c.localName==b.localName&&d++;segs.unshift(b.localName.toLowerCase()+"["+d+"]")}else segs.unshift(b.localName.toLowerCase()+'[@id="'+b.getAttribute("id")+'"]')}else if(b.hasAttribute("name"))segs.unshift(b.localName.toLowerCase()+'[@name="'+b.getAttribute("name")+'"]');else if(b.hasAttribute("action")&&"FORM"==b.nodeName.toUpperCase())segs.unshift(b.localName.toLowerCase()+
'[@action="'+b.getAttribute("action")+'"]');else if(b.hasAttribute("class"))segs.unshift(b.localName.toLowerCase()+'[contains(@class,"'+b.getAttribute("class")+'")]');else{d=1;for(c=b.previousSibling;c;c=c.previousSibling)c.localName==b.localName&&d++;segs.unshift(b.localName.toLowerCase()+"["+d+"]")}return segs.length?"/"+segs.join("/"):null}
function LP_lookupElementByXPath(a,b){return!a||g_isfirefox&&a&&!a.defaultView||"undefined"==(g_isfirefox?typeof a.defaultView.XPathEvaluator:typeof XPathEvaluator)?null:(g_isfirefox?new a.defaultView.XPathEvaluator:new XPathEvaluator).evaluate(b,a.documentElement,null,g_isfirefox?a.defaultView.XPathResult.FIRST_ORDERED_NODE_TYPE:XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue}
function LP_lookupElementsByXPath(a,b){var e=[];if(!a||"undefined"==(g_isfirefox?typeof a.defaultView.XPathEvaluator:typeof XPathEvaluator))return e;var d=(g_isfirefox?new a.defaultView.XPathEvaluator:new XPathEvaluator).evaluate(b,a.documentElement,null,g_isfirefox?a.defaultView.XPathResult.ORDERED_NODE_ITERATOR_TYPE:XPathResult.ORDERED_NODE_ITERATOR_TYPE,null);if(d)for(var c=d.iterateNext();c;)c&&e.push(c),c=d.iterateNext();return e}
if("undefined"==typeof Node)var Node={ELEMENT_NODE:1,ATTRIBUTE_NODE:2,TEXT_NODE:3,CDATA_SECTION_NODE:4,ENTITY_REFERENCE_NODE:5,ENTITY_NODE:6,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11,NOTATION_NODE:12};
function LP_getXPath(a){function b(a){return"undefined"!=typeof Document?a instanceof Document:a&&a.nodeType==Node.DOCUMENT_NODE}var e,d=[],c="";if(b(a))return"/";for(;a&&!b(a);a=a.nodeType==Node.ATTRIBUTE_NODE?a.ownerElement:a.parentNode){e=d[d.length]={};switch(a.nodeType){case Node.TEXT_NODE:e.name="text()";break;case Node.ATTRIBUTE_NODE:e.name="@"+a.nodeName;break;case Node.PROCESSING_INSTRUCTION_NODE:e.name="processing-instruction()";break;case Node.COMMENT_NODE:e.name="comment()";break;case Node.ELEMENT_NODE:e.name=
a.nodeName}var f;f=1;var g=void 0;if(a.nodeType==Node.ATTRIBUTE_NODE)f=null;else for(g=a.previousSibling;g;g=g.previousSibling)g.nodeName==a.nodeName&&++f;e.position=f}for(a=d.length-1;0<=a;a--)e=d[a],c+="/"+e.name,null!=e.position&&(c+="["+e.position+"]");return c};
